In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mtpl
import numpy as np

---------------------------------------------------------
### <center>CODE</center>
---------------------------------------------------------

In [2]:
df_unclean = pd.read_csv('unclean_products.csv')
df_unclean

,Title,Rating,Rating Count,Price,URL,Site
0,"YAWYORE Gaming PC Desktop Computer,AMD Ryzen 5...",NaN,NaN,899,https://www.newegg.com/yawyore-gaming-pc-gamin...,Newegg
1,Cooler Master Elite Pro Micro ATX Gaming PC Ry...,NaN,NaN,799,https://www.newegg.com/p/3D5-0010-00631,Newegg
2,Hoengager Horizon Gaming PC -AMD Ryzen 7 5700X...,NaN,NaN,829,https://www.newegg.com/p/3D5-003E-00T54,Newegg
3,BOSGAME P6 Gaming Mini PC Ryzen 9 6900HX (8C/1...,NaN,NaN,499,https://www.newegg.com/p/1VK-02BG-00012,Newegg
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",NaN,269,909,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg
...,...,...,...,...,...,...
3665,"Sentinel RTX 5090 AI Tower PC, 16-Core AMD Ryz...",NaN,NaN,"7,299.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244 reviews from https://skytechgaming.com/,999.99,https://www.bestbuy.com/product/skytech-gaming...,BestBuy
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,5.0,1 review,"1,049.99",https://www.bestbuy.com/product/velztorm-pilum...,BestBuy
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162 reviews,"1,699.99",https://www.bestbuy.com/product/skytech-gaming...,BestBuy
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,NaN,Not yet reviewed,"1,099.99",https://www.bestbuy.com/product/skytech-gaming...,BestBuy

In [3]:
df_unclean.isna().sum()

Title              0
Rating          2831
Rating Count    2163
Price             37
URL                0
Site               0
dtype: int64

In [4]:
df_unclean['Rating Count'].value_counts()

Rating Count
2                   240
6                   160
1                   160
5                   160
269                  80
                   ...
445                   1
723                   1
188                   1
230                   1
Not yet reviewed      1
Name: count, Length: 196, dtype: int64

In [5]:
df_unclean.dtypes

Title           object
Rating          object
Rating Count    object
Price           object
URL             object
Site            object
dtype: object

In [6]:
df_unclean[df_unclean['Price'].isna()]

,Title,Rating,Rating Count,Price,URL,Site
2939,"STGAubron Gaming PC Computer Desktop, Intel 10...",3.,624,NaN,https://www.amazon.com/STGAubron-Gaming-Comput...,Amazon
2941,"Skytech Gaming Azure 3 Desktop PC, Ryzen 7 970...",4.3,48,NaN,https://www.amazon.com/Skytech-Gaming-Desktop-...,Amazon
3082,"Skytech Gaming King 95 Gaming PC, AMD Ryzen 7 ...",4.,29,NaN,https://www.amazon.com/Skytech-Gaming-Desktop-...,Amazon
3094,GMKtec Gaming Mini PC AMD Ryzen 7 H 255 (Upgra...,4.3,425,NaN,https://www.amazon.com/GMKtec-Upgraded-Compute...,Amazon
3177,GMKtec Gaming Mini PC AMD Ryzen 9 8945HS (Turb...,4.,376,NaN,https://www.amazon.com/GMKtec-Computers-Oculin...,Amazon
3189,"Skytech Gaming O11 Vision Gaming PC, AMD Ryzen...",4.,19,NaN,https://www.amazon.com/Skytech-Vision-Gaming-D...,Amazon
3192,Skytech Chronos Gaming PC Desktop - AMD Ryzen ...,4.0,125,NaN,https://www.amazon.com/Skytech-Chronos-Gaming-...,Amazon
3216,Dell Inspiron Gaming PC Desktop AMD Ryzen 7 27...,4.1,525,NaN,https://www.amazon.com/Dell-Inspiron-Desktop-P...,Amazon
3235,"Skytech Gaming Shiva Gaming PC, AMD Ryzen 5 56...",4.1,20,NaN,https://www.amazon.com/Skytech-Gaming-5600GT-3...,Amazon
3237,Velztorm Pilum Gaming Desktop PC (AMD Ryzen 7 ...,.0,1,NaN,https://www.amazon.com/Velztorm-Gaming-Desktop...,Amazon
3244,"Skytech Gaming Azure 3 Gaming PC, Intel i5 144...",2.,2,NaN,https://www.amazon.com/Skytech-Gaming-14400F-2...,Amazon
3280,"Skytech Gaming Azure 3 Gaming PC, AMD Ryzen 7 ...",4.0,1,NaN,https://www.amazon.com/Skytech-Azure-Gaming-De...,Amazon
3363,"Skytech Gaming O11 Vision Gaming PC, AMD Ryzen...",4.9,11,NaN,https://www.amazon.com/Skytech-Vision-Gaming-D...,Amazon
3371,"Skytech Gaming King 95 Desktop PC, Ryzen 7 980...",4.4,47,NaN,https://www.amazon.com/Skytech-Gaming-Desktop-...,Amazon
3386,msi Aegis R2 AI Gaming Desktop | Intel 24-Core...,.0,4,NaN,https://www.amazon.com/msi-Desktop-24-Core-GeF...,Amazon
3394,"Skytech Gaming O11 Vision Gaming PC, AMD Ryzen...",4.,226,NaN,https://www.amazon.com/Skytech-Gaming-Vision-9...,Amazon
3395,"CLX Set Gaming PC - AMD Ryzen 9 9900X 4.4GHz, ...",.0,7,NaN,https://www.amazon.com/CLX-Set-Gaming-PC-GeFor...,Amazon
3398,"Skytech Gaming Aqua Gaming PC, AMD Ryzen 7 980...",4.4,10,NaN,https://www.amazon.com/Skytech-Gaming-9800X3D-...,Amazon
3414,"Skytech Gaming O11 Vision Desktop PC, Ryzen 7 ...",4.3,575,NaN,https://www.amazon.com/Skytech-Gaming-Vision-D...,Amazon
3415,"Skytech O11V Gaming PC Desktop, Intel i7 14700...",4.1,12,NaN,https://www.amazon.com/Skytech-Gaming-Desktop-...,Amazon
3417,"Skytech Gaming Azure 3 Plus Gaming PC, AMD Ryz...",4.3,430,NaN,https://www.amazon.com/Skytech-Gaming-7800X3D-...,Amazon
3425,Dell Alienware Aurora ACT1250 Gaming AI Deskto...,.0,2,NaN,https://www.amazon.com/Dell-Alienware-Ultra-26...,Amazon
3433,msi Aegis RS2 AI Gaming Desktop: Intel Ultra 7...,4.2,52,NaN,https://www.amazon.com/MSI-Aegis-Gaming-Deskto...,Amazon
3435,XIDAX X-6 Series AMD Ryzen 7 9800X3D 4.7GHz (M...,.0,1,NaN,https://www.amazon.com/XIDAX-9800X3D-Genuine-A...,Amazon
3436,"Skytech Gaming King 95 Desktop PC, Ryzen 9 990...",3.7,15,NaN,https://www.amazon.com/Skytech-Gaming-Desktop-...,Amazon
3443,Skytech Gaming Azure Gaming PC Desktop – AMD R...,4.1,109,NaN,https://www.amazon.com/Skytech-Gaming-Azure-PC...,Amazon
3444,"Omen by HP Obelisk Gaming Desktop Computer, 9t...",4.4,737,NaN,https://www.amazon.com/HP-Computer-Generation-...,Amazon
3445,"OMEN 30L Gaming Desktop PC, NVIDIA GeForce RTX...",4.1,"1,123",NaN,https://www.amazon.com/OMEN-Generation-i7-1070...,Amazon
3449,"CyberPowerPC Gamer Xtreme VR Gaming PC, Intel ...",4.3,435,NaN,https://www.amazon.com/CyberpowerPC-i9-13900KF...,Amazon
3456,Lenovo Legion T7 34IRZ8 Desktop Core i9-13900K...,4.2,5,NaN,https://www.amazon.com/Lenovo-Desktop-i9-13900...,Amazon
3460,Cooler Master NR2 Pro Mini ITX – Intel i7-1470...,3.9,16,NaN,https://www.amazon.com/Cooler-Master-NR2-Pro-M...,Amazon
3465,NUC 15 Pro+ NUC15CRSU9 Elegant Mini PC with In...,.0,5,NaN,https://www.amazon.com/NUC15CRSU9-Processor-Th...,Amazon
3560,"Skytech Legacy 4 Gaming PC Desktop, Ryzen 9 99...",.0,7,NaN,https://www.amazon.com/Skytech-Legacy-Gaming-D...,Amazon
3564,"Skytech Gaming Legacy 4 Gaming PC, Intel Ultra...",4.1,6,NaN,https://www.amazon.com/Skytech-Gaming-Legacy-5...,Amazon
3565,"Skytech Gaming Prism 4 Desktop PC, Intel Ultra...",4.0,1,NaN,https://www.amazon.com/Skytech-Gaming-Prism-De...,Amazon
3566,"CYBERPOWERPC Gamer Supreme Gaming PC, AMD Ryze...",3.1,6,NaN,https://www.amazon.com/CyberPowerPC-Supreme-Ge...,Amazon
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,NaN,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon

In [7]:
df_unclean['URL'].iloc[3237]

'https://www.amazon.com/Velztorm-Gaming-Desktop-GeForce-Display/dp/B0FC96688Z/ref=sr_1_263?dib=eyJ2IjoiMSJ9.mT46PIGPLEz11ss3aSwaoNWj_PKLEmzHp7Ove2cckp4XHD279VEyEgUqI81RP3JmOdH9TrBTL82MpZt3tVGHHRu_Js7C0pfS6g8i76JyiAb37TtEaiV44J5KPQc13EoqLQ7jvDEA5qrX-FHC6C9QWIh4bgrQERWWlOmvgB177l7GZ8XbZ2tKw6sLosl6kd3S7Aq6zIXgSwthSDgDyogXOa0pyP3DS9vq03pICkZZHYI.rs8654SEH4U8_mSM9_KOEFYIbaVTqtvGtcfiABSCm1c&dib_tag=se&keywords=pre+built+pc+gaming&qid=1770869853&refinements=p_36%3A-250000&sr=8-263'

In [8]:
df_unclean[df_unclean['Rating'] == '.0']

,Title,Rating,Rating Count,Price,URL,Site
2884,"STGAubron Gaming PC Computer Desktop, Intel Co...",.0,8,408.,https://www.amazon.com/STGAubron-Gaming-Comput...,Amazon
2897,"Skytech Gaming Crystal Gaming PC, AMD Ryzen 7 ...",.0,5,"1,199.",https://www.amazon.com/Skytech-Gaming-Crystal-...,Amazon
2923,"Skytech Gaming Azure 3 Gaming PC, AMD Ryzen 7 ...",.0,NaN,"1,159.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
2971,"Skytech Gaming Rampage Gaming PC, AMD Ryzen 7 ...",.0,1,"1,999.",https://www.amazon.com/Skytech-Gaming-Rampage-...,Amazon
3015,"ACEMAGIC K1 Mini PC Windows 11 Pro, Intel Core...",.0,2,399.,https://www.amazon.com/ACEMAGIC-K1-Windows-Com...,Amazon
...,...,...,...,...,...,...
3645,"Mantis V2 - RTX 5090, 24-Core Ultra 9 285K, 12...",.0,NaN,"6,999.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3650,"Mantis V2 - RTX 5090, 24-Core Ultra 9 285K, 12...",.0,NaN,"6,999.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3655,"Mantis V2 - RTX 5090, 24-Core Ultra 9 285K, 12...",.0,NaN,"6,999.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3660,"Mantis V2 - RTX 5090, 24-Core Ultra 9 285K, 12...",.0,NaN,"6,999.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3661,"Panorama XL RTX 5090, 24-Core Ultra 9 285K, 12...",.0,NaN,"7,399.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon

In [9]:
df_unclean[df_unclean['Title'].duplicated()== True]

,Title,Rating,Rating Count,Price,URL,Site
36,"YAWYORE Gaming PC Desktop Computer,AMD Ryzen 5...",NaN,NaN,899,https://www.newegg.com/yawyore-gaming-pc-gamin...,Newegg
37,Cooler Master Elite Pro Micro ATX Gaming PC Ry...,NaN,NaN,799,https://www.newegg.com/p/3D5-0010-00631,Newegg
38,Hoengager Horizon Gaming PC -AMD Ryzen 7 5700X...,NaN,NaN,829,https://www.newegg.com/p/3D5-003E-00T54,Newegg
39,BOSGAME P6 Gaming Mini PC Ryzen 9 6900HX (8C/1...,NaN,NaN,499,https://www.newegg.com/p/1VK-02BG-00012,Newegg
40,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",NaN,269,909,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg
...,...,...,...,...,...,...
3661,"Panorama XL RTX 5090, 24-Core Ultra 9 285K, 12...",.0,NaN,"7,399.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3662,"Panorama XL RTX 5090, Ryzen 7 9800X3D, 64GB DD...",4.9,NaN,"5,999.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3663,"Continuum Micro RTX 5090 Gamer PC, AMD 8-Core ...",NaN,NaN,"5,299.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3664,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3665,"Sentinel RTX 5090 AI Tower PC, 16-Core AMD Ryz...",NaN,NaN,"7,299.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon

In [10]:
df_unclean['Title'].iloc[3664]

'Panorama RTX 5090, 24-Core i9-13900KF, 32GB DDR5 RAM, 2TB NVMe SSD, Liquid Cooled Gaming Desktop PC w/Windows 11 Pro, 3-Year Warranty, RGB Keyboard+Mouse, Internal Wi-Fi 6E, RJ45, 3X DP & HDMI'

In [11]:
df_unclean[df_unclean['Title'] == 'Panorama RTX 5090, 24-Core i9-13900KF, 32GB DDR5 RAM, 2TB NVMe SSD, Liquid Cooled Gaming Desktop PC w/Windows 11 Pro, 3-Year Warranty, RGB Keyboard+Mouse, Internal Wi-Fi 6E, RJ45, 3X DP & HDMI']

,Title,Rating,Rating Count,Price,URL,Site
3546,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3570,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3575,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3581,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3588,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3593,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3599,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3604,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3609,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3614,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3619,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3624,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3629,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3634,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3639,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3644,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3649,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3654,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3659,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon
3664,"Panorama RTX 5090, 24-Core i9-13900KF, 32GB DD...",NaN,NaN,"5,499.",https://www.amazon.com/sspa/click?ie=UTF8&spc=...,Amazon

TODO:

- [X] Drop or replace NaN values
- [X] Format Price
- [ ] Feature engineer from Title
- [X] Look into Rating Count and Rating
- [X] Drop Duplicates

In [12]:
df_undupe = df_unclean.drop_duplicates()

## Look into Rating Count and Rating

In [13]:
rating_count_list = df_undupe['Rating Count'].value_counts().index.to_list()

In [14]:
df_undupe = df_undupe.copy()
df_temp = df_undupe['Rating Count'].str.replace(r'\b(reviews|review|from|,)\b', '', regex = True).str.replace(r'https?://[^\s<>"]+', '', regex = True).str.strip().copy()

In [15]:
df_undupe['Rating Count'] = df_temp

In [16]:
df_undupe['Rating Count'].isna().sum()

425

In [17]:
len(df_undupe['Rating Count'])

826

In [18]:
df_undupe['Rating'] = df_undupe['Rating'].str.replace(r'\b(rated|out|of|5)\b', '', regex = True)
df_undupe['Rating'].value_counts().index.tolist()

['.0',
 '4.4',
 '4.',
 '4.2',
 '4.3',
 '4.1',
 '4.6',
 '4.0',
 '3.8',
 '4.7',
 '4.9',
 '3.0',
 '3.9',
 '3.7',
 '4.8',
 '3.6',
 '3.1',
 '1.0',
 '3.',
 '3.2',
 '3.4',
 '2.',
 ' 4.3   ',
 ' 4.6   ',
 '1.1',
 '2.9']

In [19]:
df_undupe['Rating'] = df_undupe['Rating'].replace('2.', '2.0')
df_undupe['Rating'].value_counts().index.tolist()

['.0',
 '4.4',
 '4.',
 '4.2',
 '4.3',
 '4.1',
 '4.6',
 '4.0',
 '3.8',
 '4.7',
 '4.9',
 '3.0',
 '3.9',
 '3.7',
 '4.8',
 '3.6',
 '3.1',
 '1.0',
 '3.',
 '3.2',
 '3.4',
 '2.0',
 ' 4.3   ',
 ' 4.6   ',
 '1.1',
 '2.9']

In [20]:
df_undupe['Rating'] = df_undupe['Rating'].str.strip()
df_undupe['Rating'].value_counts().index.tolist()

['.0',
 '4.4',
 '4.',
 '4.2',
 '4.3',
 '4.1',
 '4.6',
 '4.0',
 '3.8',
 '4.7',
 '4.9',
 '3.0',
 '3.9',
 '3.7',
 '4.8',
 '3.6',
 '1.0',
 '3.',
 '3.1',
 '3.2',
 '3.4',
 '2.0',
 '1.1',
 '2.9']

In [21]:
df_undupe['Rating'].isna().sum()

224

## Drop/Fill NAs

In [22]:
df_clean = df_undupe.dropna(subset = ['Rating Count'])
df_clean

,Title,Rating,Rating Count,Price,URL,Site
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",NaN,269,909,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,NaN,2,939,https://www.newegg.com/p/3D5-003E-00H23,Newegg
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,NaN,1,624,https://www.newegg.com/viprtech-stryker-gaming...,Newegg
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,NaN,1,"1,152",https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg
...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,NaN,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.99,https://www.bestbuy.com/product/skytech-gaming...,BestBuy
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,.0,1,"1,049.99",https://www.bestbuy.com/product/velztorm-pilum...,BestBuy
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,"1,699.99",https://www.bestbuy.com/product/skytech-gaming...,BestBuy
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,NaN,Not yet reviewed,"1,099.99",https://www.bestbuy.com/product/skytech-gaming...,BestBuy

In [23]:
#Quickly format price
df_clean['Price'] = df_clean['Price'].str.replace(r'\..*', '', regex = True)
df_clean['Price'] = df_clean['Price'].str.replace(',', '').str.strip()

C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\3484158442.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Price'] = df_clean['Price'].str.replace(r'\..*', '', regex = True)
C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\3484158442.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Price'] = df_clean['Price'].str.replace(',', '').str.strip()

In [24]:
df_clean['Rating'] = pd.to_numeric(df_clean['Rating'], errors = 'coerce')
df_clean.dtypes

C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\1572141001.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Rating'] = pd.to_numeric(df_clean['Rating'], errors = 'coerce')

Title            object
Rating          float64
Rating Count     object
Price            object
URL              object
Site             object
dtype: object

In [25]:
df_clean['Rating Count'] = pd.to_numeric(df_clean['Rating Count'], errors = 'coerce').astype('Int64')
df_clean.dtypes

C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\2349952541.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Rating Count'] = pd.to_numeric(df_clean['Rating Count'], errors = 'coerce').astype('Int64')

Title            object
Rating          float64
Rating Count      Int64
Price            object
URL              object
Site             object
dtype: object

In [26]:
df_clean['Price'] = pd.to_numeric(df_clean['Price'], errors = 'coerce')
df_clean.dtypes

C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\2769473169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Price'] = pd.to_numeric(df_clean['Price'], errors = 'coerce')

Title            object
Rating          float64
Rating Count      Int64
Price           float64
URL              object
Site             object
dtype: object

In [27]:
df_clean['Rating'] = df_clean['Rating'].fillna(df_clean['Rating'].median())
df_clean['Rating']

C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\1058888886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Rating'] = df_clean['Rating'].fillna(df_clean['Rating'].median())

4       4.1
8       4.1
11      4.3
12      4.1
14      4.1
       ...
3567    4.2
3666    4.7
3667    0.0
3668    4.7
3669    4.1
Name: Rating, Length: 401, dtype: float64

In [28]:
df_clean['Rating'].isna().sum()

0

In [29]:
df_clean['Rating Count'].isna().sum()

1

In [30]:
df_clean['Price'].isna().sum()

37

In [31]:
df_clean['Price'].median()

1299.0

In [32]:
na_indexs = df_clean['Price'].isna()

In [33]:
na_indexs

4       False
8       False
11      False
12      False
14      False
        ...
3567     True
3666    False
3667    False
3668    False
3669    False
Name: Price, Length: 401, dtype: bool

In [34]:
df_clean['Price'] = df_clean['Price'].fillna(df_clean['Price'].median())

C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\1635206145.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Price'] = df_clean['Price'].fillna(df_clean['Price'].median())

In [35]:
df_clean['Price'].isna().sum()

0

In [36]:
df_clean

,Title,Rating,Rating Count,Price,URL,Site
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg
...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,0.0,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,<NA>,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy

<center>==================================</center>
<center><h3>Feature Engineer Titles</h3></center>
<center>==================================</center>

In [37]:
df_unfinished = df_clean.copy()

In [38]:
df_unfinished['Rating Count'].fillna(df_unfinished['Rating Count'].median().astype(int))

4       269
8         2
11        6
12        1
14        1
       ...
3567    156
3666    244
3667      1
3668    162
3669     35
Name: Rating Count, Length: 401, dtype: Int64

In [39]:
df_unfinished['Rating Count'].isna().sum()

1

In [40]:
index = df_unfinished[df_unfinished['Rating Count'].isna()].index
index[0]

3669

In [41]:
median =  int(df_unfinished['Rating Count'].median())
df_unfinished.loc[index[0], 'Rating Count'] = median

In [42]:
df_unfinished['Rating Count'].isna().sum()

0

In [43]:
df_unfinished['Rating Count']

4       269
8         2
11        6
12        1
14        1
       ...
3567    156
3666    244
3667      1
3668    162
3669     35
Name: Rating Count, Length: 401, dtype: Int64

In [44]:
df_unfinished['Title'] = df_unfinished['Title'].astype(str)

In [45]:
df_unfinished.dtypes

Title            object
Rating          float64
Rating Count      Int64
Price           float64
URL              object
Site             object
dtype: object

In [46]:
patterns = {
    'cpu': r'(Intel\s+(?:\d+(?:st|nd|rd|th)\s+Gen\s+[A-Z]?\d+[A-Z]*|(?:Quad\s+)?(?:Core[™®]*\s+)?(?:i[3579]|Ultra)\s*[-\s]?\d+[A-Z]*)|(?:AMD\s+)?R[579]-?\s*\d+[A-Z]*|(?:AMD\s+)?Ryzen[™®]*\s*\d*\s+(?:\d+\s+\d+[XGETH3D]*|[a-zA-Z0-9-]+)|Core[™®\s]+[Ii][3579](?:\s+Upto.*?GHz)?|i[3579]\s+CPU|Xeon\s+E\d+)',
    'gpu': r'(NVIDIA\s+(?:GeForce\s+)?RTX\s+\d+|AMD\s+(?:Radeon\s+RX\s+\d+|RX\s+\d+)|(?:GeForce\s+GTX\s+\d+))',
    'ram': r'(\d+(?:\.\d+)?\s*(?:GB\s*)?(?:DDR[45]))',
    'storage': r'(\d+(?:\.\d+)?\s*(?:TB|GB)\s*(?:NVMe|SSD|M\.2|PCIe))',
    'os': r'(Windows\s+(?:11|10)\s*(?:Home|Pro)?)'
}

In [47]:
import re
df_unfinished['CPU'] = df_unfinished['Title'].str.extract(patterns['cpu'], flags=re.IGNORECASE)[0]
df_unfinished['GPU'] = df_unfinished['Title'].str.extract(patterns['gpu'], flags=re.IGNORECASE)[0] 
df_unfinished['RAM'] = df_unfinished['Title'].str.extract(patterns['ram'], flags=re.IGNORECASE)[0]
df_unfinished['Storage'] = df_unfinished['Title'].str.extract(patterns['storage'], flags=re.IGNORECASE)[0]
df_unfinished['OS'] = df_unfinished['Title'].str.extract(patterns['os'], flags=re.IGNORECASE)[0]

In [48]:
df_unfinished

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NaN,32GB DDR4,1TB NVME,Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NaN,16GB DDR4,1TB M.2,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,Ryzen 5 5600G,NaN,NaN,1TB NVME,Windows 10
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5-9400F,AMD RX 580,16GB DDR4,500GB SSD,NaN
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA GeForce RTX 5060,16GB DDR5,NaN,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NaN,64GB DDR5,2TB M.2,Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,NaN,NaN,NaN,NaN
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,0.0,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NaN,NaN,1TB SSD,Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA GeForce RTX 5060,NaN,1TB NVMe,NaN
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel Core i5 14400F,NaN,NaN,NaN,NaN

In [49]:
df_unfinished['CPU'].isna().sum()

27

In [50]:
df_unfinished['Title'].loc[3548]

'Thermaltake LCGS View 9890S-380XL Gaming Desktop (AMD Ryzen™ 7 9800X3D, 32GB 6000MT/s DDR5 RGB Memory, NVIDIA® GeForce RTX™ 5090, 2TB NVMe M.2, WiFi, Windows 11) VXLS-X870-590-LCS'

In [51]:
df_unfinished[df_unfinished['CPU'].isna() == True]

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
2888,"ASUS ROG G700 (2025) Gaming Desktop PC, Intel®...",4.3,101,1899.0,https://www.amazon.com/ASUS-Desktop-Processor-...,Amazon,NaN,NaN,32GB DDR5,1TB M.2,Windows 11 Home
2940,Lenovo Legion Tower 5i – AI-Powered Gaming PC ...,4.9,67,2111.0,https://www.amazon.com/Lenovo-Legion-Tower-AI-...,Amazon,NaN,NaN,NaN,NaN,NaN
2959,NOVATECH Phantom - Prebuilt Gaming PC Desktop ...,4.1,221,689.0,https://www.amazon.com/NOVATECH-Phantom-Prebui...,Amazon,NaN,NaN,NaN,512GB M.2,NaN
2964,Dell Optiplex Small Desktop Computer (SFF) PC ...,3.7,558,349.0,https://www.amazon.com/Dell-Optiplex-Desktop-C...,Amazon,NaN,NaN,NaN,512GB SSD,Windows 11 Pro
3015,"ACEMAGIC K1 Mini PC Windows 11 Pro, Intel Core...",0.0,2,399.0,https://www.amazon.com/ACEMAGIC-K1-Windows-Com...,Amazon,NaN,NaN,16GB DDR4,512GB SSD,Windows 11 Pro
3031,"MUSETEX ATX PC Case, 6 PWM ARGB Fans Pre-Insta...",4.6,845,76.0,https://www.amazon.com/MUSETEX-Pre-Installed-S...,Amazon,NaN,NaN,NaN,NaN,NaN
3040,Lenovo Legion Tower 5i Gaming PC - Intel® Core...,4.2,21,1401.0,https://www.amazon.com/Lenovo-Legion-Tower-AI-...,Amazon,NaN,NaN,NaN,NaN,Windows 11 Home
3059,Dell Optiplex 3060 (RGB) Desktop Computer | He...,4.0,32,427.0,https://www.amazon.com/Dell-Optiplex-7050-Comp...,Amazon,NaN,NaN,16GB DDR4,1TB SSD,Windows 11 Pro
3064,"ASUS ROG G700 (2025) Gaming Desktop PC, Intel®...",4.1,53,2099.0,https://www.amazon.com/ASUS-Desktop-Processor-...,Amazon,NaN,NaN,32GB DDR5,1TB M.2,Windows 11 Pro
3092,"KAMRUI Pinova P2 Mini PC, W-11 Pro in-tel Core...",4.3,120,399.0,https://www.amazon.com/KAMRUI-Pinova-P2-Comput...,Amazon,NaN,NaN,NaN,512GB SSD,NaN
3145,Sceptre New Curved 24.5-inch Gaming Monitor up...,4.4,5401,119.0,https://www.amazon.com/Sceptre-24-5-inch-Displ...,Amazon,NaN,NaN,NaN,NaN,NaN
3174,"KAMRUI Hyper H2 Mini Gaming PC, Intel Core 144...",4.6,187,519.0,https://www.amazon.com/KAMRUI-14450HX-Computer...,Amazon,NaN,NaN,NaN,NaN,NaN
3223,ASUS ROG Strix Helios GX601 RGB Mid-Tower Gami...,4.7,1607,269.0,https://www.amazon.com/GX601-Mid-Tower-Compute...,Amazon,NaN,NaN,NaN,NaN,NaN
3227,Lenovo ThinkCentre M700 SFF Gaming Desktop Com...,4.8,6,371.0,https://www.amazon.com/Lenovo-ThinkCentre-M700...,Amazon,NaN,NaN,NaN,1TB SSD,Windows 10 Pro
3236,HP Windows 11 Desktop Computer | 16GB RAM + 50...,3.7,50,344.0,https://www.amazon.com/HP-Windows-Computer-Key...,Amazon,NaN,NaN,NaN,500GB SSD,Windows 11
3256,ASUS ROG Strix Scope II 96 Wireless Mechanical...,4.6,863,129.0,https://www.amazon.com/ASUS-II-Switch-Dampenin...,Amazon,NaN,NaN,NaN,NaN,NaN
3322,"Skytech Gaming Legacy 4 Desktop PC, Ultra 9 28...",4.2,52,3499.0,https://www.amazon.com/Skytech-Gaming-Legacy-D...,Amazon,NaN,NVIDIA RTX 5080,64GB DDR5,NaN,NaN
3349,"Skytech Gaming Chronos 3 Desktop PC, Ultra 7 2...",3.8,8,2699.0,https://www.amazon.com/Skytech-Gaming-Chronos-...,Amazon,NaN,NVIDIA RTX 5080,32GB DDR5,2TB NVMe,NaN
3362,ASUS ROG Strix G700 Desktop 11TB Storage + SSD...,0.0,2,3299.0,https://www.amazon.com/ASUS-ROG-G16CH-i9-14900...,Amazon,NaN,NaN,128GB DDR5,NaN,NaN
3382,ORIGIN PC Neuron Gaming PC – Liquid Cooled Int...,4.6,3,2899.0,https://www.amazon.com/Origin-PC-Neuron-Gaming...,Amazon,NaN,NaN,NaN,2TB M.2,NaN
3404,"Panorama XL RTX 5080, Intel 24-Core Ultra 9 28...",4.7,46,3299.0,https://www.amazon.com/Panorama-PC-Processor-W...,Amazon,NaN,NaN,32GB DDR5,NaN,Windows 11 Pro
3425,Dell Alienware Aurora ACT1250 Gaming AI Deskto...,0.0,2,1299.0,https://www.amazon.com/Dell-Alienware-Ultra-26...,Amazon,NaN,NaN,NaN,1TB SSD,NaN
3434,Skytech Legacy 3.0 Gaming PC Desktop - Intel C...,4.0,71,3999.0,https://www.amazon.com/Skytech-Legacy-3-0-Gami...,Amazon,NaN,NaN,16GB DDR4,1TB NVME,Windows 10 Home
3438,"Mantis RTX 5080, 20-Core Ultra 7 265KF, 32GB D...",0.0,1,2849.0,https://www.amazon.com/Mantis-PC-Warranty-Keyb...,Amazon,NaN,NaN,32GB DDR5,NaN,Windows 11 Pro
3543,Corsair Vengeance i8300 Gaming PC – Liquid Coo...,4.8,6,7499.0,https://www.amazon.com/Corsair-Vengeance-i8300...,Amazon,NaN,NaN,NaN,4TB M.2,NaN
3557,"Mantis V2 - RTX 5090, 24-Core Ultra 9 285K, 64...",0.0,1,5999.0,https://www.amazon.com/Mantis-V2-Warranty-Keyb...,Amazon,NaN,NaN,64GB DDR5,NaN,Windows 11 Pro
3558,"Mantis V2 - RTX 5090, Ultra 7 265KF, 64GB DDR5...",0.0,1,5499.0,https://www.amazon.com/Mantis-V2-WaterCooled-W...,Amazon,NaN,NaN,64GB DDR5,2TB NVMe,Windows 11 Pro

In [52]:
df_unfinished.loc[2888, 'CPU'] = 'Intel Ultra 7 265KF'
df_unfinished.loc[2940, 'CPU'] = 'Intel Core Ultra 7 265F'
df_unfinished.loc[2959, 'CPU'] = 'Intel i7 Xeon'
df_unfinished.loc[2964, 'CPU'] = 'Intel i5'
df_unfinished.loc[3015, 'CPU'] = 'Intel 12600H'
df_unfinished.loc[3174, 'CPU'] = 'Intel 14450HX'
df_unfinished.loc[3040, 'CPU'] = 'Intel Ultra 7 265F'
df_unfinished.loc[3059, 'CPU'] = 'Hexa Core Intel i5'
df_unfinished.loc[3064, 'CPU'] = 'Intel Core Ultra 7 265F'
df_unfinished.loc[3092, 'CPU'] = 'Intel Core 12600H'
df_unfinished.loc[3227, 'CPU'] = 'Intel Core i7 6700'
df_unfinished.loc[3236, 'CPU'] = 'Intel i5'
df_unfinished.loc[3322, 'CPU'] = 'Intel Ultra 9 285K'
df_unfinished.loc[3349, 'CPU'] = 'Intel Ultra 7 265K'
df_unfinished.loc[3362, 'CPU'] = 'Intel Core Ultra 9'
df_unfinished.loc[3382, 'CPU'] = 'Intel Core Ultra 7 265K'
df_unfinished.loc[3404, 'CPU'] = 'Intel Ultra 9 286K'
df_unfinished.loc[3425, 'CPU'] = 'Intel Ultra 7 265F'
df_unfinished.loc[3434, 'CPU'] = 'Intel Core i7 9700K'
df_unfinished.loc[3438, 'CPU'] = 'Intel Ultra 7 265K'
df_unfinished.loc[3543, 'CPU'] = 'Intel Core Ultra 9 285K'
df_unfinished.loc[3557, 'CPU'] = 'Intel Core Ultra 9 285K'
df_unfinished.loc[3558, 'CPU'] = 'Intel Core Ultra 7 265KF'

In [53]:
df_unfinished['Title'].loc[3558]

'Mantis V2 - RTX 5090, Ultra 7 265KF, 64GB DDR5 RAM, 2TB NVMe Gen5 SSD, WaterCooled Gaming Desktop PC w/Windows 11 Pro, 3-Year Warranty, RGB Gamer Keyboard+Mouse, Internal Wi-Fi 7 + BT, RJ45, DP & HDMI'

In [54]:
df_unfinished.dropna(subset = 'CPU', inplace = True)
df_unfinished

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NaN,32GB DDR4,1TB NVME,Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NaN,16GB DDR4,1TB M.2,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,Ryzen 5 5600G,NaN,NaN,1TB NVME,Windows 10
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5-9400F,AMD RX 580,16GB DDR4,500GB SSD,NaN
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA GeForce RTX 5060,16GB DDR5,NaN,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NaN,64GB DDR5,2TB M.2,Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,NaN,NaN,NaN,NaN
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,0.0,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NaN,NaN,1TB SSD,Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA GeForce RTX 5060,NaN,1TB NVMe,NaN
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel Core i5 14400F,NaN,NaN,NaN,NaN

In [55]:
df_CPU = df_unfinished['CPU']

In [56]:
patterns = {
    #'cpu': r'(Intel\s+(?:\d+(?:st|nd|rd|th)\s+Gen\s+[A-Z]?\d+[A-Z]*|(?:Quad\s+)?(?:Core[™®]*\s+)?(?:i[3579]|Ultra)\s*[-\s]?\d+[A-Z]*)|(?:AMD\s+)?R[579]-?\s*\d+[A-Z]*|(?:AMD\s+)?Ryzen[™®]*\s*\d*\s+(?:\d+\s+\d+[XGETH3D]*|[a-zA-Z0-9-]+)|Core[™®\s]+[Ii][3579](?:\s+Upto.*?GHz)?|i[3579]\s+CPU|Xeon\s+E\d+)',
    'gpu': r'((?:NVIDIA[®™]?\s*)?(?:GeForce[®™]?\s*)?(?:RTX|GTX|GT)[®™]?\s*-?\s*\d{3,4}(?:\s?Ti|\s?SUPER)?|(?:AMD[®™]?\s*)?(?:Radeon[®™]?\s*(?:RX\s*)?|RX\s+)\d{3,4}(?:\s?(?:XT|XTX|GRE))?|\d{3,4}\s?(?:XT|XTX|GRE)|Vega\s+(?:Graphics|\d+)|Intel[®™]?\s*Arc[™]?\s*[A-Z]?\d+|Integrated\s+Radeon)',
    'ram': r'(\d+(?:\.\d+)?\s*(?:GB\s*)?(?:DDR[45]))',
    'storage': r'(\d+(?:\.\d+)?\s*(?:TB|GB)\s*(?:NVMe|SSD|M\.2|PCIe))',
    'os': r'(Windows\s+(?:11|10)\s*(?:Home|Pro)?)'
}

In [57]:
df_unfinished['GPU'].isna().sum()

209

In [58]:
import re
df_unfinished['GPU'] = df_unfinished['Title'].str.extract(patterns['gpu'], flags=re.IGNORECASE)[0]

In [59]:
df_unfinished[df_unfinished['GPU'].isna()]['Title'].tolist()

['YEAH MAGIC Astral S1 Gaming Desktop AMD Ryzen 5 5600GT (6 core up to 4.6GHz) 16GB DDR4 3200MHz 1TB NVMe SSD 650W Gold PSU Windows 11 Home WIFI Gaming PC with 7 ARGB Fans',
 'GenMachine Mini PC AMD Ryzen 5 5500U,16GB RAM 512GB M.2 NVMe SSD,AMD Radeon Graphics,2 x 4K Output, 2 x HDMI Ports,2 x USB 3.0,1 x Type-C,Wifi6,Bluetooth5.2,Windows 10 Pro Desktop Computer',
 'YEAH MAGIC Astral  S1 Gaming Desktop AMD Ryzen 5 5600GT 3.9GHz 16GB(8G*2) DDR4 3200 1T NVME SSD 7 ARGB Fan*7 Win 11 Home WIFI Gamer Desktop Computer Office Work 650W Gold PSU Black',
 'Prebuilt Gaming PC Desktop Computer,Intel Core i7 Desktop,Operating at A Frequency of 3.4-3.9 GHz,RX590 Graphics Card with 8GB GDDR5 Video Memory,16GB RAM, 512GB SSD,WiFi 5.0,RGB Fan x4',
 'PC Gaming Desktop AMD Ryzen 7 5700G RAM 16G 3200MHz DDR4 1TB M.2 Prebuilt Computer Tower 550W Bronze Power Supply ARGB Air Colling Computer for Office Game',
 'Pre-Built Gaming PC Desktop Computer – Xeon E5 Up to 3.60GHz, RX580 8GB,16 GB RAM,512GB SSD,1TB HDD,Wi-Fi 6 & Bluetooth 5.4, 9× ARGB Fans, Windows 11,Home or Office PC',
 'Dell Optiplex Small Desktop Computer (SFF) PC | Quad Core Intel i5 (3.2GHz) | 16GB DDR3 RAM | 512GB SSD | 24 Inch Monitor | RGB Gaming Keyboard & Mouse, Headset | Windows 11 Pro (Renewed)',
 'KAMRUI Hyper H1 Mini Gaming PC, AMD Ryzen 7 6800H, 32GB DDR5 (Upgradable, Not LPDDR) 512GB NVMe SSD Mini PC(8C/16T,up to 4.7GHz), 16MB L3 Smart Cache, Triple 4K Display/WiFi6/BT5.2/Mini Desktop PC',
 'Dell OptiPlex Desktop RGB Computer PC, Intel Core i7 Core Processor, 16G RAM, 512G SSD, 24 Inch HDMI Monitor, RGB Keyboard & Mouse & Headset, WiFi, Windows 11 Pro (Renewed)',
 'HP ProDesk Desktop RGB Lights Computer Intel Core i5 6500 3.2 GHz 8GB RAM 256GB SSD Gaming PC Keyboard & Mouse, Windows 11 Pro (Renewed)',
 'STGAubron RGB PC Computer Desktop, AMD Ryzen 7 5700G up to 4.6G, 16GB DDR4, 1TB SSD, WiFi 6 & BT 5.2, RGB Fan x4, RGB Keyboard & Mouse, Windows 11 Home',
 'Dell OptiPlex RGB Desktop Computer PC, Intel Core i7, 16G RAM, 512G SSD, New 22 inch FHD Monitor, RGB Keyboard & Mouse, RGB Headphone, Webcam, WiFi, BT 5.0, Windows 11 Pro (Renewed)',
 'ACEMAGIC K1 Mini PC Windows 11 Pro, Intel Core 12600H (Beat 12450H up to 4.5 GHz) Mini Computers, 16GB DDR4 RAM 512GB SSD Triple 4K Display Desktop Micro Small Pc with BT5.2/WiFi6/HDMI/USB3.2',
 'BOSGAME P2 Plus Mini PC - Intel i7-12700H, 32GB DDR5, 512GB NVMe SSD | Win11 Pro | Thunderbolt 4, 4K Triple Display | 2.5G Ethernet + WiFi 6E | Ultra-Compact Desktop Computer',
 'BOSGAME E5 Multi-Functional Mini PC, Ryzen 3 5300U 4-core 8-Thread Dual LAN Desktop Computers, 16GB DDR4 1TB PCIe 3.0x4 SSD, Triple Displays HDMI 2.0x1, DisplayPortx1, USB-C x1, Wi-Fi 5, BT 5.0',
 'ACEMAGIC Mini PC Gaming AMD Ryzen 7 7730U (Upgraded 7430U/ 5825U) Windows 11 Pro 32GB RAM 1TB SSD Triple 4K@60Hz Display WiFi6 BT5.2 Type-C HDMI DP1.4b Mini Computers Desktop for Light Gaming/Office',
 'BOSGAME P6 Ryzen 9 6900HX Mini PC Gaming, 32GB LPDDR5X Mini Computers, 1TB PCIe4.0 NVMe SSD, Dual LAN, AX210 Wi-Fi 6E, BT 5.3, Triple Display 4K, Light Gaming, Office and Home',
 'Dell Optiplex 3060 (RGB) Desktop Computer | Hexa Core Intel i5 (3.2) | 16GB DDR4 RAM | 1TB SSD | 24" LCD | Windows 11 Professional | Home or Office PC (Renewed)',
 'GMKtec Gaming PC, K11 AMD Ryzen 9 8945HS(8C/16T, Up to 5.2GHz), 32GB DDR5 RAM 1TB Mini PC Desktop Computer, Oculink, Dual NIC 2.5GbE LAN, HDMI/DisplayPort/USB4*2',
 'Dell Optiplex 7040 SFF Intel Core i5-6500, 16GB Ram, 256GB SSD, DVD-RW, WiFi ，Win 11 Pro (Renewed)',
 'KAMRUI Pinova P2 Mini PC, W-11 Pro in-tel Core 12600H (12C/16T, up to 4.5GHz) 16GB RAM 512GB SSD Mini Desktop Computer, Triple 4K Display HDMI+DP+Type-C, 6*USB3.2, WiFi6, BT5.2, Business Home Office',
 'GMKtec Gaming Mini PC AMD Ryzen 7 H 255 (Upgraded 8745HS) 32GB DDR5 1TB SSD, Desktop Computer 3XM.2 2280 Expansion, Oculink, Dual NIC 2.5G, HDMI 2.1, USB4 K12',
 'KAMRUI E3B Mini PC with AMD Ryzen 7 5700U (Beat 5500U, up to 4.3GHz), 16GB DDR4 512GB M.2 SSD Mini Computer, Mini Gaming PC with USB Type-C Supports Triple 4K Display, WiFi 6, BT 5.2',
 'HP ProDesk 400 G5 SFF High Performance RGB Desktop Computer, Intel Quad-Core i3-8100 3.60 GHz, 16G DDR4, 1T SSD, WiFi, BT, DP, Windows 11 64 (Renewed)',
 'Dell OptiPlex Computer Desktop PC, Intel Core i5 3rd Gen 3.2 GHz, 16GB RAM, 2TB HDD, New 22 Inch LED Monitor, RGB Keyboard and Mouse, WiFi, Windows 11 Pro (Renewed)',
 'KAMRUI Pinova P1 Mini PC Computer, AMD Ryzen 4300U Processor, 16GB DDR4 RAM 256GB M.2 SSD, Mini Desktop Computer Support Triple 4K, USB-C, WiFi, Bluetooth, Ethernet, HTPC for Business, Education, Home',
 'ACEMAGICIAN Kron Mini K1 Mini PC, Ryzen 7 7730U(Upgraded 5825U/7430U), 16GB DDR4 512GB SSD Mini Computers(up to 4.5Ghz), Light Gaming Desktop 4K Triple Display Mini Desktop Bluetooth/WiFi6/Office',
 'KAMRUI Hyper H2 Mini Gaming PC, Intel Core 14450HX Mini Computers (10C/16T, 4.8GHz), 32GB RAM 1TB PCle4.0 SSD Micro Desktop PC, Triple 4K Display, USB Type-C, WiFi6, BT5.2, Business Office Home',
 'GMKtec Gaming Mini PC AMD Ryzen 9 8945HS (Turbo 5.1GHz) 32GB DDR5 2TB SSD, Computers PC Oculink, Dual NIC LAN 2.5G, WiFi 6, USB3.2, USB-C 4.0, BT5.2, DP, HDMI, Dual Fan Nucbox K11',
 'KAMRUI Pinova P2 Mini PC 16GB RAM 512GB SSD, AMD Ryzen 4300U(Beats 3500U/3550H/N150/N95,Up to 3.7 GHz) Mini Computers,Triple 4K Display/HDMI+DP+Type-C/WiFi/BT for Home/Business Mini Desktop Computers',
 'HP Prodesk 600 G6 Tower PC Desktop Computer, Intel Core i5-10500 Up to 4.50 GHz, 16GB DDR4 Ram, 512GB NVMe SSD, RGB Keyboard Mouse, Windows 11 Pro (Renewed)',
 'Dell Optiplex 3050 SFF Desktop Computer PC, Intel Quad Core i5-6500 up to 3.6GHz, 16GB DDR4, 256GB SSD, WiFi, 4K Support, DP, HDMI, Windows 11 Pro 64 Bit (Renewed)',
 'GEEKOM IT13 Mini PC 2026 Edition with Intel 13th Gen i9-13900HK, 16GB RAM(Not LPDDR)&1TB NVMe SSD (Expandable), NUC13 Mini Desktop Computer Windows 11 Pro for Home&Office | 8K UHD,USB4,WiFi 6E,BT5.2',
 'KAMRUI Mini PC, E3B 32GB RAM 512GB SSD Mini Gaming Computers AMD Ryzen 5 7430U Micro Desktop Computer (Max 4.3GHz,6C/12T, Beat 5650U), Small PC Support WiFi 6, BT5.2, Triple Display for Office Home',
 'Lenovo ThinkCentre M700 Tiny Desktop PC with 24" FHD Monitor, Intel Quad Core i5-6500, 16GB DDR4 RAM 256GB SSD, 2 DisplayPort, Keyboard & Mouse, WiFi, Windows 11 Pro (Renewed)',
 'HP ProDesk 600 G6 Tower PC Desktop Computer, Six-Core i5-10500 Up to 4.50 GHz, 16GB DDR4, 256GB SSD, Keyboard and Mouse, WiFi, BT, 4K Support, Windows 11 Pro (Renewed)',
 'HP Envy Desktop, 11th Gen Intel Core i7-11700, 16 GB RAM, 512 GB SSD & 1 TB SATA Hard Drive, Windows 11 Pro, Wi-Fi & Bluetooth, Wired Keyboard & Mouse, Pre-Built PC Tower',
 'ASUS ROG Hyperion GR701 EATX Full-Tower Computer case with Semi-Open Structure, Tool-Free Side Panels, Supports up to 2 x 420mm radiators, Built-in Graphics Card Holder, 2X Front Panel Type-C',
 'Skytech Gaming Shiva Gaming PC, AMD Ryzen 5 5600GT 3.6GHz, 500GB NVMe SSD, 16GB DDR4 RAM 3200, 650W Gold PSU, Wi-Fi, Win 11, Desktop',
 'HP Windows 11 Desktop Computer | 16GB RAM + 500GB SSD | Intel i5 | 16GB RAM + 500GB SSD | 24" LCD | WiFi 6 AX200 + BT | RGB Keyboard/Mouse + Speakers | Webcam | Home or Office PC (Renewed)',
 'HP Pavilion Gaming PC, AMD Ryzen 3 5300G Processor, 8 GB RAM, 256 GB SSD, Windows 11, Wi-Fi 5 & Bluetooth 4.2 Combo, 9 USB Ports, Pre-Built Gaming PC Tower, Mouse and Keyboard (TG01-2010, 2021)',
 'GEEKOM IT15, The Most Powerful AI Mini PC with Intel Ultra 9 285H(15th Gen) 99 Tops | 32GB DDR5, 2TB SSD | Arc 140T GPU | WiFi 7, 8K Quad Display, Win11 Pro, Video Editing, Coding, and Multitasking',
 'BOSGAME P3 Mix Mini PC Ryzen 7640HS (up to 5.0 GHz), 32GB DDR5, 1TB PCIe SSD Mini Desktop Computer, 4K Triple Display, USB 4.0, Dual 2.5G LAN & Wi-Fi 6E & BT5.2, for Home, Office, Gaming',
 'Dell Premium Desktop Computer PC, Intel Quad Core i5 3.2GHz, 16gb RAM, 1TB HDD, DVD, Bluetooth, WiFi, Compatible with Dell OptiPlex 9020 (Renewed)',
 'ASUS ROG Strix G700 Desktop 11TB Storage + SSD 128GB DDR5 RAM Win 11 Pro (Intel 15th gen Core Ultra 9 Processor Turbo Boost to 6.00GHz, NVIDIA GeForce 4060Ti RTX 8GB GDDR6) Gaming PC Computer G700TF',
 'Alienware Aurora R16 Desktop 1TB SSD 96GB DDR5 RAM Win 11 Pro (Intel 14th Generation Core i9-14900K Processor with Turbo Boost to 6.00GHz, NVIDIA GeForce RTX 8GB GDDR6) Gaming PC Business Computer',
 'NUC 15 Pro+ NUC15CRSU9 Elegant Mini PC with Intel Core Ultra 9 Processor, Arc Graphics, Dual HDMI, Thunderbolt 4 | Ideal for Work, Gaming & Creativity (64GB DDR5-5600/1TB SSD)',
 'Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5700, 5050 8GB, 16GB 3200 MHz DDR4 SDRAM, 650W GOLD PSU - White']

In [60]:
df_unfinished['GPU'].fillna('Integrated', inplace = True)
df_unfinished['GPU']

C:\Users\rishd\AppData\Local\Temp\ipykernel_9324\784848959.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_unfinished['GPU'].fillna('Integrated', inplace = True)

4                          RTX5060
8                 GeForce RTX 3050
11               Integrated Radeon
12                      AMD RX 580
14         NVIDIA GeForce RTX 5060
                   ...
3567              Geforce RTX 5090
3666                    Integrated
3667              GeForce RTX 5060
3668    NVIDIA GeForce RTX 5060 Ti
3669                        9060XT
Name: GPU, Length: 397, dtype: object

In [61]:
df_unfinished['GPU'].isna().sum()

0

In [62]:
df_GPU = df_unfinished['GPU']

In [63]:
patterns = {
    #'cpu': r'(Intel\s+(?:\d+(?:st|nd|rd|th)\s+Gen\s+[A-Z]?\d+[A-Z]*|(?:Quad\s+)?(?:Core[™®]*\s+)?(?:i[3579]|Ultra)\s*[-\s]?\d+[A-Z]*)|(?:AMD\s+)?R[579]-?\s*\d+[A-Z]*|(?:AMD\s+)?Ryzen[™®]*\s*\d*\s+(?:\d+\s+\d+[XGETH3D]*|[a-zA-Z0-9-]+)|Core[™®\s]+[Ii][3579](?:\s+Upto.*?GHz)?|i[3579]\s+CPU|Xeon\s+E\d+)',
    #'gpu': r'((?:NVIDIA[®™]?\s*)?(?:GeForce[®™]?\s*)?(?:RTX|GTX|GT)[®™]?\s*-?\s*\d{3,4}(?:\s?Ti|\s?SUPER)?|(?:AMD[®™]?\s*)?(?:Radeon[®™]?\s*(?:RX\s*)?|RX\s+)\d{3,4}(?:\s?(?:XT|XTX|GRE))?|\d{3,4}\s?(?:XT|XTX|GRE)|Vega\s+(?:Graphics|\d+)|Intel[®™]?\s*Arc[™]?\s*[A-Z]?\d+|Integrated\s+Radeon)',
    'ram': r'(?i)((?:RAM\s+)?\d+\s*G(?:B)?\s*(?:(?:(?!GDDR|Video|RTX|GTX|SSD|HDD)[\w\(\)\*\-\.\/]+)\s*){0,6}?(?:DDR\d|LPDDR\d\w*|SDRAM|RAM|Memory|DIMM))',
    'storage': r'(\d+(?:\.\d+)?\s*(?:TB|GB)\s*(?:NVMe|SSD|M\.2|PCIe))',
    'os': r'(Windows\s+(?:11|10)\s*(?:Home|Pro)?)'
}

In [64]:
df_unfinished['RAM'] = df_unfinished['Title'].str.extract(patterns['ram'], flags=re.IGNORECASE)[0]

In [65]:
df_unfinished['RAM'].isna().sum()

1

In [66]:
df_unfinished[df_unfinished['RAM'].isna() == True]['Title'].tolist()

['ASUS ROG Hyperion GR701 EATX Full-Tower Computer case with Semi-Open Structure, Tool-Free Side Panels, Supports up to 2 x 420mm radiators, Built-in Graphics Card Holder, 2X Front Panel Type-C']

In [67]:
df_unfinished['RAM'] = df_unfinished['RAM'].fillna(df_unfinished['RAM'].mode()[0])

In [68]:
df_unfinished['RAM']

4                32GB DDR4
8           6GB -16GB DDR4
11       16GB 3200MHz DDR4
12               16GB DDR4
14               16GB DDR5
               ...
3567             64GB DDR5
3666    16GB 3200 MHz DDR4
3667           32GB Memory
3668           16GB Memory
3669    16GB 3200 MHz DDR4
Name: RAM, Length: 397, dtype: object

In [69]:
df_RAM = df_unfinished['RAM']

In [70]:
patterns = {
    #'cpu': r'(Intel\s+(?:\d+(?:st|nd|rd|th)\s+Gen\s+[A-Z]?\d+[A-Z]*|(?:Quad\s+)?(?:Core[™®]*\s+)?(?:i[3579]|Ultra)\s*[-\s]?\d+[A-Z]*)|(?:AMD\s+)?R[579]-?\s*\d+[A-Z]*|(?:AMD\s+)?Ryzen[™®]*\s*\d*\s+(?:\d+\s+\d+[XGETH3D]*|[a-zA-Z0-9-]+)|Core[™®\s]+[Ii][3579](?:\s+Upto.*?GHz)?|i[3579]\s+CPU|Xeon\s+E\d+)',
    #'gpu': r'((?:NVIDIA[®™]?\s*)?(?:GeForce[®™]?\s*)?(?:RTX|GTX|GT)[®™]?\s*-?\s*\d{3,4}(?:\s?Ti|\s?SUPER)?|(?:AMD[®™]?\s*)?(?:Radeon[®™]?\s*(?:RX\s*)?|RX\s+)\d{3,4}(?:\s?(?:XT|XTX|GRE))?|\d{3,4}\s?(?:XT|XTX|GRE)|Vega\s+(?:Graphics|\d+)|Intel[®™]?\s*Arc[™]?\s*[A-Z]?\d+|Integrated\s+Radeon)',
    #'ram': r'(?i)((?:RAM\s+)?\d+\s*G(?:B)?\s*(?:(?:(?!GDDR|Video|RTX|GTX|SSD|HDD)[\w\(\)\*\-\.\/]+)\s*){0,6}?(?:DDR\d|LPDDR\d\w*|SDRAM|RAM|Memory|DIMM))',
    'storage': r'(?i)(\d+(?:\.\d+)?\s*[TG]B?\b.*? (?:SSD|NVMe|M\.2|HDD|Hard Drive|Storage))',
    'os': r'(Windows\s+(?:11|10)\s*(?:Home|Pro)?)'
}

In [71]:
df_unfinished['Storage'] = df_unfinished['Title'].str.extract(patterns['storage'], flags=re.IGNORECASE)[0]

In [72]:
df_unfinished[df_unfinished['Storage'].isna() == True]['Title'].tolist()

['LXZ Gaming PC Desktop Ryzen 7 8700F | 32GB DDR5 RAM | GeForce RTX 5060 8GB | High-Performance Gaming & Design Computer, Black Tower PC',
 'GMKtec Gaming PC, K11 AMD Ryzen 9 8945HS(8C/16T, Up to 5.2GHz), 32GB DDR5 RAM 1TB Mini PC Desktop Computer, Oculink, Dual NIC 2.5GbE LAN, HDMI/DisplayPort/USB4*2',
 'ASUS ROG Hyperion GR701 EATX Full-Tower Computer case with Semi-Open Structure, Tool-Free Side Panels, Supports up to 2 x 420mm radiators, Built-in Graphics Card Holder, 2X Front Panel Type-C',
 'Corsair Vengeance i7400 Series Gaming PC - Liquid Cooled Intel® Core™ i7 13700K CPU - NVIDIA® GeForce RTX™ 4070 Ti Graphics - 32GB Vengeance RGB DDR5 Memory, Black',
 'Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5700, 5050 8GB, 16GB 3200 MHz DDR4 SDRAM, 650W GOLD PSU - White',
 'Skytech Gaming - Skytech AZURE3 - Intel Core i5 14400F, 9060XT 8GB, 16GB 3200 MHz DDR4 SDRAM, 650W GOLD PSU - White']

In [73]:
df_unfinished['Storage'] = df_unfinished['Storage'].fillna(df_unfinished['Storage'].mode()[0])

In [74]:
df_unfinished['Storage'].isna().sum()

0

In [75]:
df_Storage = df_unfinished['Storage']

In [76]:
df_unfinished

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,RTX5060,32GB DDR4,"8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME",Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,GeForce RTX 3050,6GB -16GB DDR4,6GB -16GB DDR4 3200MHz- 1TB M.2,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,Ryzen 5 5600G,Integrated Radeon,16GB 3200MHz DDR4,"5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB ...",Windows 10
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5-9400F,AMD RX 580,16GB DDR4,"8GB, 16GB DDR4, 500GB SSD",NaN
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA GeForce RTX 5060,16GB DDR5,16GB DDR5 RGB RAM 1TB Gen 4 SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,Geforce RTX 5090,64GB DDR5,"64GB DDR5, 2TB M.2",Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",NaN
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,0.0,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,GeForce RTX 5060,32GB Memory,"32GB Memory, 1TB SSD",Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA GeForce RTX 5060 Ti,16GB Memory,16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB ...,NaN
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel Core i5 14400F,9060XT,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",NaN

In [77]:
df_unfinished['Storage'].isna().sum()

0

In [78]:
df_unfinished['OS'].isna().sum()

223

In [79]:
patterns = {
    #'cpu': r'(Intel\s+(?:\d+(?:st|nd|rd|th)\s+Gen\s+[A-Z]?\d+[A-Z]*|(?:Quad\s+)?(?:Core[™®]*\s+)?(?:i[3579]|Ultra)\s*[-\s]?\d+[A-Z]*)|(?:AMD\s+)?R[579]-?\s*\d+[A-Z]*|(?:AMD\s+)?Ryzen[™®]*\s*\d*\s+(?:\d+\s+\d+[XGETH3D]*|[a-zA-Z0-9-]+)|Core[™®\s]+[Ii][3579](?:\s+Upto.*?GHz)?|i[3579]\s+CPU|Xeon\s+E\d+)',
    #'gpu': r'((?:NVIDIA[®™]?\s*)?(?:GeForce[®™]?\s*)?(?:RTX|GTX|GT)[®™]?\s*-?\s*\d{3,4}(?:\s?Ti|\s?SUPER)?|(?:AMD[®™]?\s*)?(?:Radeon[®™]?\s*(?:RX\s*)?|RX\s+)\d{3,4}(?:\s?(?:XT|XTX|GRE))?|\d{3,4}\s?(?:XT|XTX|GRE)|Vega\s+(?:Graphics|\d+)|Intel[®™]?\s*Arc[™]?\s*[A-Z]?\d+|Integrated\s+Radeon)',
    #'ram': r'(?i)((?:RAM\s+)?\d+\s*G(?:B)?\s*(?:(?:(?!GDDR|Video|RTX|GTX|SSD|HDD)[\w\(\)\*\-\.\/]+)\s*){0,6}?(?:DDR\d|LPDDR\d\w*|SDRAM|RAM|Memory|DIMM))',
    #'storage': r'(?i)(\d+(?:\.\d+)?\s*[TG]B?\b.*? (?:SSD|NVMe|M\.2|HDD|Hard Drive|Storage))',
    'os': r'(?i)((?:Windows?|Win|W)[\s-]*?(?:10|11)(?:\s*(?:Home|Pro|Professional))?)'
}

In [80]:
df_unfinished['OS'] = df_unfinished['Title'].str.extract(patterns['os'], flags=re.IGNORECASE)[0]

In [81]:
df_unfinished['OS'].mode()[0]

'Win 11'

In [82]:
df_unfinished['OS'] = df_unfinished['OS'].fillna(df_unfinished['OS'].mode()[0])
df_unfinished['OS']

4            Windows 11
8            Windows 11
11           Windows 10
12           Win 11 Pro
14      Windows 11 Home
             ...
3567     Windows 11 Pro
3666             Win 11
3667         Windows 11
3668             Win 11
3669             Win 11
Name: OS, Length: 397, dtype: object

In [83]:
df_unfinished['OS'].isna().sum()

0

In [84]:
df_OS = df_unfinished['OS']

## <center>Cleaning Feature Engineered Columns</center>

In [85]:
df_unfinishedv2 = df_unfinished.copy()

In [86]:
df_unfinishedv2

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,RTX5060,32GB DDR4,"8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME",Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,GeForce RTX 3050,6GB -16GB DDR4,6GB -16GB DDR4 3200MHz- 1TB M.2,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,Ryzen 5 5600G,Integrated Radeon,16GB 3200MHz DDR4,"5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB ...",Windows 10
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5-9400F,AMD RX 580,16GB DDR4,"8GB, 16GB DDR4, 500GB SSD",Win 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA GeForce RTX 5060,16GB DDR5,16GB DDR5 RGB RAM 1TB Gen 4 SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,Geforce RTX 5090,64GB DDR5,"64GB DDR5, 2TB M.2",Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,0.0,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,GeForce RTX 5060,32GB Memory,"32GB Memory, 1TB SSD",Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA GeForce RTX 5060 Ti,16GB Memory,16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB ...,Win 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel Core i5 14400F,9060XT,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11

In [87]:
df_unfinishedv2['CPU'].value_counts().index.tolist()

['Ryzen 7 9800X3D',
 'AMD Ryzen 7 9800X3D',
 'Intel i5 14400F',
 'Ryzen 7 9700X',
 'AMD Ryzen 7 7800X3D',
 'AMD Ryzen 7 9700X',
 'Core i9',
 'AMD Ryzen 7 7700 3',
 'AMD Ryzen 7 5700X',
 'Core i7',
 'AMD Ryzen 5 5600GT',
 'Intel Ultra 9',
 'Intel i7 14700F',
 'Ryzen 7 7800X3D',
 'Intel Core Ultra 9',
 'Ryzen 5 5500 3',
 'Core i5',
 'AMD Ryzen 7 7700X',
 'Intel i9-14900K',
 'Intel Ultra 7',
 'Ryzen 7 7700X',
 'Intel Core Ultra 7',
 'Ryzen 5 9600X',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 5 5500 3',
 'AMD Ryzen™ 7 9800X3D',
 'AMD Ryzen 7 5700G',
 'Ryzen 7 7700 3',
 'AMD Ryzen 7 8700F',
 'Ryzen 7 5700 3',
 'Intel i5 13400F',
 'Ryzen 9 9900X',
 'Intel Quad Core I5-6500',
 'Ryzen 9 9900X3D',
 'AMD Ryzen 5 5600X',
 'Intel Core i9-14900KF',
 'Ryzen 7 5700X',
 'Intel Core i7 14700F',
 'Intel Core i9 14900KF',
 'AMD Ryzen 7 5700 3',
 'Core I7',
 'AMD Ryzen 9 9900X',
 'Intel Core™ i5-14400F',
 'Intel Quad Core i5-6500',
 'Intel Ultra 7 265F',
 'Intel Core Ultra 9 285K',
 'AMD Ryzen 7 260',
 'AMD Ryzen 5 7600 3',
 'AMD Ryzen AI',
 'Intel Ultra 7 265K',
 'Core™ i9',
 'Ryzen 7 5800X',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 4300U',
 'Ryzen 9 9950X3D',
 'Intel Core i5-6500',
 'AMD Ryzen 7 3800X',
 'Intel Core i7-14700KF',
 'AMD RYZEN 7 9800X3D',
 'AMD Ryzen 3 5300G',
 'Intel Core i5-13400F',
 'AMD Ryzen 7 6800H',
 'AMD Ryzen 5 9600X',
 'Intel Core i7-14700F',
 'Intel Core I7 8th',
 'Intel Core Ultra 7 265F',
 'AMD Ryzen 5 5600',
 'AMD R7-8700F',
 'Intel i5',
 'Intel Core™ i9-14900KF',
 'Intel 10th Gen G5905',
 'Intel Core i5-12400F',
 'AMD Ryzen 7',
 'Intel Core i5-14400F',
 'R5 6400MT',
 'Intel i9 14900K',
 'Intel Ultra 9 285K',
 'AMD Ryzen 5 5500U',
 'AMD Ryzen 5 4500 6X',
 'AMD Ryzen 9 7900X',
 'AMD Ryzen™ 7 7800X3D',
 'Intel Core i3-10105',
 'Intel Quad Core i5 3',
 'AMD Ryzen 7 H255',
 'Intel Core i5-11600KF',
 'Intel Core i5-8500',
 'Ryzen 7640HS',
 'Intel Core i7 6th',
 'Intel Core i3-10100F',
 'Intel Ultra 7 265KF',
 'Intel Core i7-6700',
 'AMD Ryzen 5 7500F',
 'R5 2TB',
 'Intel Core i9-13900F',
 'Intel Core i9 12900KF',
 'AMD Ryzen 7 5700',
 'AMD Ryzen 9 9950X',
 'AMD Ryzen™ 9 9950X3D',
 'Intel Core Ultra 7 265KF',
 'AMD Ryzen 9 9950X3D',
 'Ryzen 5 5600G',
 'Intel i7-14700F',
 'Intel i5-9400F',
 'AMD Ryzen 7 7700',
 'Intel Core i9-13900KF',
 'Intel Core i7-10700KF',
 'Intel Core Ultra 7 265K',
 'Intel Core i9-9900K',
 'Intel Core i7-13700KF',
 'Intel Core i7 9700K',
 'Intel Core i7-10700K',
 'Intel i9-12900F',
 'Intel i7 14700K',
 'Intel Ultra 9 286K',
 'Core™ i7',
 'Intel i5-10400F',
 'AMD R9-9900X',
 'AMD Ryzen5 6Cores',
 'Intel Core i3-10100',
 'Intel Core i7 6700',
 'Ryzen 5 7600X',
 'Core i3',
 'AMD Ryzen 7 5700U',
 'AMD Ryzen 7 H',
 'Intel Core 12600H',
 'Xeon E5',
 'AMD Ryzen 5 3400G',
 'Hexa Core Intel i5',
 'Ryzen 9 6900HX',
 'AMD Ryzen 7 7730U',
 'Ryzen 5-4',
 'Intel Core i5-7500',
 'AMD Ryzen 3 3200G',
 'Ryzen 3 5300U',
 'Intel i7 Xeon',
 'Intel i7-12700H',
 'AMD Ryzen 7 with',
 'AMD Ryzen 5 4X',
 'Intel 12600H',
 'AMD Ryzen R9-7900X',
 'Intel Core i5-10400F',
 'Intel Core i5 6500',
 'Intel Core i5-11400F',
 'AMD RYZEN 5 5600X',
 'Ryzen 5 5500',
 'AMD Ryzen™ 5 7600X',
 'R701',
 'Intel Core i7-11700',
 'AMD Ryzen 7 2700',
 'Intel Core Ultra 5',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 7 8745HS',
 'Intel 13th Gen i9',
 'Core™ i5',
 'Intel Core i5-10500',
 'AMD Ryzen 9 3900X',
 'Ryzen 7 8700F',
 'Intel Core i7 13700F',
 'Intel 14450HX',
 'i7 CPU',
 'Ryzen 7 7730U',
 'AMD R5 5500',
 'Intel Core i5-9400F',
 'AMD Ryzen 5 2600',
 'Core I9 Upto 5.4Ghz',
 'Intel Core i5 3rd',
 'Intel Core i5 14400F']

In [88]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('[™®]','', regex = True)

In [89]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('-', ' ')

In [90]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('CPU', '')

In [91]:
df_unfinishedv2['CPU'] = np.where(
    df_unfinishedv2['CPU'].str.contains('ryzen', case=False, na=False) & 
    ~df_unfinishedv2['CPU'].str.contains('AMD', case=False, na=False),
    'AMD ' + df_unfinishedv2['CPU'],
    df_unfinishedv2['CPU']
)

In [92]:
df_unfinishedv2['CPU'] = np.where(
    df_unfinishedv2['CPU'].str.contains('core', case = False, na=False) & 
    ~df_unfinishedv2['CPU'].str.contains('Intel', case = False, na=False),
    'Intel ' + df_unfinishedv2['CPU'],
    df_unfinishedv2['CPU']
)

In [93]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen 7 7700 3', 'AMD Ryzen 7 7700')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Core', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen 7 5700 3', 'AMD Ryzen 7 5700')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('I5', 'i5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Quad Core', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('RYZEN', 'Ryzen')

In [94]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Quad', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('I7', 'i7')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen 5 5500 3', 'AMD Ryzen 5 5500')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen 5 7600 3', 'AMD Ryzen 5 7600')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AI', '5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('R701', 'R7')

df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('R7', 'Ryzen 7')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('R5', 'Ryzen 5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('  ', ' ')

In [95]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Xeon E5', 'Intel Xeon E5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('13th Gen', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen 7 H', 'AMD Ryzen 7')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('6th', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Hexa', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('3rd', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Ryzen 5 2TB', 'Ryzen 5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('i7', 'Intel i7')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('  ', ' ')

In [96]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Intel Intel', 'Intel')

In [97]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Upto 5.4Ghz', '')

In [98]:
df_unfinishedv2['CPU'].value_counts().index.tolist()

['AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 7800X3D',
 'Intel i5 14400F',
 'AMD Ryzen 5 5500',
 'Intel Ultra 9',
 'AMD Ryzen 7 7700',
 'Intel i7 14700F',
 'Intel i7',
 'Intel i9',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 7700X',
 'Intel Ultra 7',
 'Intel i5',
 'Intel i9 14900KF',
 'AMD Ryzen 7 5700',
 'Intel i5 6500',
 'AMD Ryzen 5 5600GT',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 9 9900X',
 'Intel i9 14900K',
 'AMD Ryzen 5 9600X',
 'Intel i5 13400F',
 'AMD Ryzen 5 5600X',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 9 9950X3D',
 'Intel Ultra 7 265F',
 'Intel Ultra 7 265K',
 'Intel Ultra 9 285K',
 'AMD Ryzen 9 9900X3D',
 'AMD Ryzen 7',
 'AMD Ryzen 7 5800X',
 'Intel i7 6700',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 5 7600X',
 'AMD Ryzen 7 7730U',
 'AMD Ryzen 7 3800X',
 'Intel 12600H',
 'AMD Ryzen 4300U',
 'Intel i7 14700KF',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 7 6800H',
 'Intel i7 ',
 'Intel i5 10400F',
 'AMD Ryzen 7 260',
 'Intel i5 9400F',
 'AMD Ryzen 5',
 'AMD Ryzen 5 5600',
 'Intel Ultra 7 265KF',
 'Intel i5 12400F',
 'Intel 10th Gen G5905',
 'Intel i7 8th',
 'Intel i9 12900KF',
 'Intel i7 10700KF',
 'Intel i5 8500',
 'AMD Ryzen 7640HS',
 'Intel i9 13900KF',
 'AMD Ryzen 7255',
 'Intel i3 10100F',
 'Ryzen 7',
 'Intel i5 11600KF',
 'Ryzen 5',
 'Intel i5 3',
 'AMD R9 9900X',
 'Intel i9 9900K',
 'Intel i7 13700KF',
 'Intel i3 10105',
 'Intel i7 9700K',
 'Intel i7 10700K',
 'Intel i9 12900F',
 'Ryzen 5 6400MT',
 'AMD Ryzen 7 2700',
 'Intel i7 14700K',
 'Intel i9 13900F',
 'Intel Ultra 9 286K',
 'Intel i7 11700',
 'AMD Ryzen 9 6900HX',
 'Intel i3 10100',
 'AMD Ryzen 7 with',
 'AMD Ryzen 5 5600G',
 'AMD Ryzen 5 7500F',
 'AMD Ryzen 5 5500U',
 'AMD Ryzen 9 7900X',
 'Intel AMD Ryzen5 6s',
 'AMD Ryzen 5 2600',
 'Intel I9 ',
 'Intel Xeon E5',
 'AMD Ryzen 5 3400G',
 'Intel i7 Xeon',
 'AMD Ryzen 5 4X',
 'AMD Ryzen 5 4500 6X',
 'Intel Ultra 5',
 'AMD Ryzen R9 7900X',
 'Intel i7 12700H',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 3 3200G',
 'Intel i5 7500',
 'AMD Ryzen 5 4',
 ' Intel i5',
 'AMD Ryzen 7 5700U',
 'Intel i3',
 'Intel i5 11400F',
 'Intel i5 ',
 'Intel 14450HX',
 'Intel i7 13700F',
 'AMD Ryzen 9 3900X',
 'Intel i5 10500',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 9 9950X']

In [99]:
df_unfinishedv2['CPU'] = np.where(
    df_unfinishedv2['CPU'].str.contains('ryzen', case=False, na=False) & 
    ~df_unfinishedv2['CPU'].str.contains('AMD', case=False, na=False),
    'AMD ' + df_unfinishedv2['CPU'],
    df_unfinishedv2['CPU']
)

In [100]:
df_unfinishedv2['CPU'].value_counts().index.tolist()

['AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 7800X3D',
 'Intel i5 14400F',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 7 7700',
 'Intel Ultra 9',
 'Intel i7 14700F',
 'Intel i9',
 'Intel i7',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 7700X',
 'Intel i5',
 'Intel Ultra 7',
 'AMD Ryzen 5 5600GT',
 'AMD Ryzen 7 5700',
 'Intel i5 6500',
 'Intel i9 14900KF',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 5 9600X',
 'Intel i9 14900K',
 'AMD Ryzen 9 9900X',
 'Intel i5 13400F',
 'Intel Ultra 7 265F',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 5 5600X',
 'AMD Ryzen 7',
 'AMD Ryzen 9 9950X3D',
 'AMD Ryzen 9 9900X3D',
 'Intel Ultra 9 285K',
 'AMD Ryzen 5',
 'Intel Ultra 7 265K',
 'AMD Ryzen 7 260',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 5 7600X',
 'Intel 12600H',
 'AMD Ryzen 7 5800X',
 'Intel i7 14700KF',
 'AMD Ryzen 7 3800X',
 'AMD Ryzen 4300U',
 'Intel i7 6700',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 7 7730U',
 'Intel Ultra 7 265KF',
 'Intel i7 ',
 'Intel i5 9400F',
 'Intel 10th Gen G5905',
 'AMD Ryzen 5 5600',
 'AMD Ryzen 7 6800H',
 'Intel i5 12400F',
 'Intel i7 8th',
 'Intel i5 10400F',
 'AMD Ryzen 7255',
 'Intel i5 11600KF',
 'Intel i3 10105',
 'AMD Ryzen 9 7900X',
 'AMD Ryzen 5 5500U',
 'Intel i5 8500',
 'AMD Ryzen 7640HS',
 'Intel i3 10100F',
 'AMD Ryzen 5 6400MT',
 'Intel i5 3',
 'AMD Ryzen R9 7900X',
 'AMD Ryzen 5 7500F',
 'Intel i9 13900F',
 'Intel AMD Ryzen5 6s',
 'Intel Ultra 9 286K',
 'Intel i7 14700K',
 'Intel i9 12900F',
 'Intel i7 10700K',
 'Intel i7 9700K',
 'Intel i7 13700KF',
 'Intel i9 9900K',
 'Intel i7 10700KF',
 'Intel i9 12900KF',
 'Intel i9 13900KF',
 'AMD Ryzen 5 5600G',
 'AMD R9 9900X',
 'AMD Ryzen 5 7430U',
 'Intel i7 11700',
 'AMD Ryzen 7 5700U',
 'AMD Ryzen 5 4500 6X',
 'AMD Ryzen 7 with',
 'Intel i7 12700H',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 3 3200G',
 'Intel i5 7500',
 'AMD Ryzen 5 4',
 'AMD Ryzen 5 4X',
 'AMD Ryzen 9 6900HX',
 ' Intel i5',
 'Intel i7 Xeon',
 'AMD Ryzen 5 3400G',
 'Intel i3',
 'AMD Ryzen 7 2700',
 'Intel i5 11400F',
 'Intel Xeon E5',
 'Intel i5 ',
 'Intel I9 ',
 'AMD Ryzen 5 2600',
 'Intel 14450HX',
 'Intel i7 13700F',
 'AMD Ryzen 9 3900X',
 'Intel i5 10500',
 'AMD Ryzen 7 8745HS',
 'Intel Ultra 5',
 'Intel i3 10100',
 'AMD Ryzen 9 9950X']

In [101]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('R9', 'Ryzen 9')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('10th Gen', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('8th', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('6x', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('6s', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('with', '')

In [102]:
df_unfinishedv2['CPU'].value_counts().index.tolist()

['AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 7800X3D',
 'Intel i5 14400F',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 7 7700',
 'Intel Ultra 9',
 'Intel i7 14700F',
 'Intel i9',
 'Intel i7',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 7700X',
 'Intel i5',
 'Intel Ultra 7',
 'AMD Ryzen 5 5600GT',
 'Intel i5 6500',
 'AMD Ryzen 7 5700',
 'Intel i9 14900KF',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 9 9900X',
 'AMD Ryzen 5 9600X',
 'Intel i9 14900K',
 'Intel i5 13400F',
 'Intel Ultra 7 265F',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 5 5600X',
 'Intel i7 ',
 'AMD Ryzen 9 9950X3D',
 'AMD Ryzen 7',
 'AMD Ryzen 5',
 'Intel Ultra 7 265K',
 'Intel Ultra 9 285K',
 'AMD Ryzen 9 9900X3D',
 'Intel i7 14700KF',
 'AMD Ryzen 7 5800X',
 'Intel 12600H',
 'AMD Ryzen 4300U',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 7 3800X',
 'Intel i7 6700',
 'AMD Ryzen 5 7600X',
 'AMD Ryzen 7 260',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 7 7730U',
 'Intel i5 9400F',
 'Intel i5 10400F',
 'AMD Ryzen 5 5600',
 'AMD Ryzen 7 6800H',
 'Intel  G5905',
 'Intel i5 12400F',
 'Intel Ultra 7 265KF',
 'Intel i5 11600KF',
 'AMD Ryzen 7255',
 'Intel i5 3',
 'AMD Ryzen 5 7500F',
 'AMD Ryzen 9 7900X',
 'Intel i5 8500',
 'AMD Ryzen 7640HS',
 'Intel i3 10100F',
 'AMD Ryzen 5 5500U',
 'AMD Ryzen 5 6400MT',
 'Intel i3 10105',
 'AMD Ryzen Ryzen 9 7900X',
 'Intel i9 13900F',
 'Intel i7 11700',
 'Intel Ultra 9 286K',
 'Intel i7 14700K',
 'Intel i9 12900F',
 'Intel i7 10700K',
 'Intel i7 9700K',
 'Intel i7 13700KF',
 'Intel i9 9900K',
 'Intel i7 10700KF',
 'Intel i9 12900KF',
 'Intel i9 13900KF',
 'AMD Ryzen 5 5600G',
 'Intel AMD Ryzen5 ',
 'Intel i3 10100',
 'AMD Ryzen 7 2700',
 'AMD Ryzen 7 ',
 'Intel Ultra 5',
 'Intel i7 12700H',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 3 3200G',
 'Intel i5 7500',
 'AMD Ryzen 5 4',
 'AMD Ryzen 5 4500 6X',
 'AMD Ryzen 9 6900HX',
 ' Intel i5',
 'AMD Ryzen 5 4X',
 'AMD Ryzen 7 5700U',
 'Intel i3',
 'Intel i5 11400F',
 'Intel i7 Xeon',
 'AMD Ryzen 5 3400G',
 'Intel i5 ',
 'Intel Xeon E5',
 'Intel I9 ',
 'Intel 14450HX',
 'Intel i7 13700F',
 'AMD Ryzen 9 3900X',
 'AMD Ryzen 5 2600',
 'Intel i5 10500',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 9 9950X']

In [103]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Intel i5 3', 'Intel 5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Intel AMD Ryzen5 ', 'AMD Ryzen 5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('6X', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen 5 4', 'AMD Ryzen 5')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('4X', '')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('I9', 'i9')
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('  ', ' ')

In [104]:
df_unfinishedv2['CPU'].value_counts().index.tolist()

['AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 7800X3D',
 'Intel i5 14400F',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 7 7700',
 'Intel Ultra 9',
 'Intel i7 14700F',
 'Intel i7',
 'Intel i9',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 7700X',
 'Intel Ultra 7',
 'Intel i5',
 'Intel i9 14900KF',
 'AMD Ryzen 5 5600GT',
 'Intel i5 6500',
 'AMD Ryzen 7 5700',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 9 9900X',
 'Intel i9 14900K',
 'AMD Ryzen 5 9600X',
 'AMD Ryzen 5',
 'Intel i5 13400F',
 'Intel Ultra 7 265F',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 5 5600X',
 'Intel i7 ',
 'AMD Ryzen 9 9950X3D',
 'AMD Ryzen 7',
 'Intel Ultra 7 265K',
 'Intel Ultra 9 285K',
 'AMD Ryzen 9 9900X3D',
 'Intel i7 14700KF',
 'AMD Ryzen 7 5800X',
 'AMD Ryzen 5 7600X',
 'AMD Ryzen 7 3800X',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 4300U',
 'Intel i7 6700',
 'Intel 12600H',
 'AMD Ryzen 7 260',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 7 7730U',
 'Intel Ultra 7 265KF',
 'Intel i5 10400F',
 'Intel i5 12400F',
 'Intel G5905',
 'AMD Ryzen 5 5600',
 'AMD Ryzen 7 6800H',
 'Intel i5 9400F',
 'AMD Ryzen 7255',
 'Intel 5',
 'AMD Ryzen 5 7500F',
 'Intel i5 11600KF',
 'AMD Ryzen 5 5500U',
 'Intel i5 8500',
 'AMD Ryzen 7640HS',
 'Intel i3 10100F',
 'AMD Ryzen 9 7900X',
 'AMD Ryzen 5 6400MT',
 'Intel i3 10105',
 'AMD Ryzen Ryzen 9 7900X',
 'Intel i7 11700',
 'Intel Ultra 9 286K',
 'Intel i7 14700K',
 'Intel i9 12900F',
 'Intel i7 10700K',
 'Intel i7 9700K',
 'Intel i7 13700KF',
 'Intel i9 9900K',
 'Intel i7 10700KF',
 'Intel i9 12900KF',
 'Intel i9 13900KF',
 'AMD Ryzen 5 5600G',
 'Intel i9 13900F',
 'Intel i3 10100',
 'AMD Ryzen 7 2700',
 'Intel i5 11400F',
 'Intel Ultra 5',
 'Intel i7 12700H',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 3 3200G',
 'Intel i5 7500',
 'AMD Ryzen 5500 ',
 'AMD Ryzen 9 6900HX',
 ' Intel i5',
 'AMD Ryzen 5X',
 'AMD Ryzen 7 5700U',
 'Intel i3',
 'Intel i7 Xeon',
 'AMD Ryzen 7 ',
 'AMD Ryzen 5 3400G',
 'Intel i5 ',
 'Intel Xeon E5',
 'Intel i9 ',
 'Intel 14450HX',
 'Intel i7 13700F',
 'AMD Ryzen 9 3900X',
 'AMD Ryzen 5 2600',
 'Intel i5 10500',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 9 9950X']

In [105]:
df_unfinishedv2['CPU'].value_counts().index.tolist()

['AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 7800X3D',
 'Intel i5 14400F',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 7 7700',
 'Intel Ultra 9',
 'Intel i7 14700F',
 'Intel i7',
 'Intel i9',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 7700X',
 'Intel Ultra 7',
 'Intel i5',
 'Intel i9 14900KF',
 'AMD Ryzen 5 5600GT',
 'Intel i5 6500',
 'AMD Ryzen 7 5700',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 9 9900X',
 'Intel i9 14900K',
 'AMD Ryzen 5 9600X',
 'AMD Ryzen 5',
 'Intel i5 13400F',
 'Intel Ultra 7 265F',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 5 5600X',
 'Intel i7 ',
 'AMD Ryzen 9 9950X3D',
 'AMD Ryzen 7',
 'Intel Ultra 7 265K',
 'Intel Ultra 9 285K',
 'AMD Ryzen 9 9900X3D',
 'Intel i7 14700KF',
 'AMD Ryzen 7 5800X',
 'AMD Ryzen 5 7600X',
 'AMD Ryzen 7 3800X',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 4300U',
 'Intel i7 6700',
 'Intel 12600H',
 'AMD Ryzen 7 260',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 7 7730U',
 'Intel Ultra 7 265KF',
 'Intel i5 10400F',
 'Intel i5 12400F',
 'Intel G5905',
 'AMD Ryzen 5 5600',
 'AMD Ryzen 7 6800H',
 'Intel i5 9400F',
 'AMD Ryzen 7255',
 'Intel 5',
 'AMD Ryzen 5 7500F',
 'Intel i5 11600KF',
 'AMD Ryzen 5 5500U',
 'Intel i5 8500',
 'AMD Ryzen 7640HS',
 'Intel i3 10100F',
 'AMD Ryzen 9 7900X',
 'AMD Ryzen 5 6400MT',
 'Intel i3 10105',
 'AMD Ryzen Ryzen 9 7900X',
 'Intel i7 11700',
 'Intel Ultra 9 286K',
 'Intel i7 14700K',
 'Intel i9 12900F',
 'Intel i7 10700K',
 'Intel i7 9700K',
 'Intel i7 13700KF',
 'Intel i9 9900K',
 'Intel i7 10700KF',
 'Intel i9 12900KF',
 'Intel i9 13900KF',
 'AMD Ryzen 5 5600G',
 'Intel i9 13900F',
 'Intel i3 10100',
 'AMD Ryzen 7 2700',
 'Intel i5 11400F',
 'Intel Ultra 5',
 'Intel i7 12700H',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 3 3200G',
 'Intel i5 7500',
 'AMD Ryzen 5500 ',
 'AMD Ryzen 9 6900HX',
 ' Intel i5',
 'AMD Ryzen 5X',
 'AMD Ryzen 7 5700U',
 'Intel i3',
 'Intel i7 Xeon',
 'AMD Ryzen 7 ',
 'AMD Ryzen 5 3400G',
 'Intel i5 ',
 'Intel Xeon E5',
 'Intel i9 ',
 'Intel 14450HX',
 'Intel i7 13700F',
 'AMD Ryzen 9 3900X',
 'AMD Ryzen 5 2600',
 'Intel i5 10500',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 9 9950X']

In [106]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.strip()

In [107]:
df_unfinishedv2['CPU'].value_counts().index.tolist()

['AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 7800X3D',
 'Intel i5 14400F',
 'Intel i7',
 'AMD Ryzen 5 5500',
 'Intel Ultra 9',
 'AMD Ryzen 7 7700',
 'Intel i7 14700F',
 'Intel i9',
 'AMD Ryzen 7 5700X',
 'Intel i5',
 'AMD Ryzen 7 7700X',
 'Intel Ultra 7',
 'AMD Ryzen 5 5600GT',
 'Intel i5 6500',
 'AMD Ryzen 7 5700',
 'Intel i9 14900KF',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 9 9900X',
 'Intel i9 14900K',
 'AMD Ryzen 5 9600X',
 'AMD Ryzen 7',
 'AMD Ryzen 5',
 'Intel i5 13400F',
 'Intel Ultra 7 265F',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 5 5600X',
 'AMD Ryzen 9 9950X3D',
 'AMD Ryzen 9 9900X3D',
 'Intel Ultra 9 285K',
 'Intel Ultra 7 265K',
 'AMD Ryzen 5 7600X',
 'Intel 12600H',
 'AMD Ryzen 4300U',
 'Intel i7 6700',
 'Intel i7 14700KF',
 'AMD Ryzen 7 5800X',
 'AMD Ryzen 7 3800X',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 7 260',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 7 7730U',
 'Intel Ultra 7 265KF',
 'Intel i5 9400F',
 'Intel i5 10400F',
 'AMD Ryzen 7 6800H',
 'AMD Ryzen 5 5600',
 'Intel i5 12400F',
 'Intel G5905',
 'AMD Ryzen 7640HS',
 'Intel i5 8500',
 'Intel i5 11600KF',
 'AMD Ryzen 7255',
 'Intel 5',
 'Intel i3 10105',
 'AMD Ryzen 5 5500U',
 'AMD Ryzen 5 6400MT',
 'AMD Ryzen 5 7500F',
 'AMD Ryzen Ryzen 9 7900X',
 'Intel i9 13900F',
 'Intel i3 10100F',
 'Intel i7 14700K',
 'Intel i9 12900F',
 'Intel i7 10700K',
 'Intel i7 9700K',
 'Intel i7 13700KF',
 'Intel i9 9900K',
 'Intel i7 10700KF',
 'Intel i9 12900KF',
 'Intel i9 13900KF',
 'AMD Ryzen 5 5600G',
 'Intel Ultra 9 286K',
 'Intel i7 11700',
 'AMD Ryzen 9 7900X',
 'Intel i7 Xeon',
 'Intel i7 12700H',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 3 3200G',
 'Intel i5 7500',
 'AMD Ryzen 5500',
 'AMD Ryzen 9 6900HX',
 'AMD Ryzen 5X',
 'AMD Ryzen 7 5700U',
 'Intel i3',
 'Intel i5 11400F',
 'AMD Ryzen 5 3400G',
 'Intel Ultra 5',
 'Intel Xeon E5',
 'Intel 14450HX',
 'Intel i7 13700F',
 'AMD Ryzen 9 3900X',
 'AMD Ryzen 5 2600',
 'Intel i5 10500',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 5 7430U',
 'Intel i3 10100',
 'AMD Ryzen 7 2700',
 'AMD Ryzen 9 9950X']

In [108]:
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('Intel 5', 'Intel i5', regex=False)
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen 7255', 'AMD Ryzen 7 255', regex=False)
df_unfinishedv2['CPU'] = df_unfinishedv2['CPU'].str.replace('AMD Ryzen Ryzen 9 7900X', 'AMD Ryzen 9 7900X', regex=False)

In [109]:
df_unfinishedv2['CPU'].value_counts().sort_index(ascending = True).index.tolist()

['AMD Ryzen 3 3200G',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 4300U',
 'AMD Ryzen 5',
 'AMD Ryzen 5 2600',
 'AMD Ryzen 5 3400G',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 5 5500U',
 'AMD Ryzen 5 5600',
 'AMD Ryzen 5 5600G',
 'AMD Ryzen 5 5600GT',
 'AMD Ryzen 5 5600X',
 'AMD Ryzen 5 6400MT',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 5 7500F',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 5 7600X',
 'AMD Ryzen 5 9600X',
 'AMD Ryzen 5500',
 'AMD Ryzen 5X',
 'AMD Ryzen 7',
 'AMD Ryzen 7 255',
 'AMD Ryzen 7 260',
 'AMD Ryzen 7 2700',
 'AMD Ryzen 7 3800X',
 'AMD Ryzen 7 5700',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 7 5700U',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 5800X',
 'AMD Ryzen 7 6800H',
 'AMD Ryzen 7 7700',
 'AMD Ryzen 7 7700X',
 'AMD Ryzen 7 7730U',
 'AMD Ryzen 7 7800X3D',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7640HS',
 'AMD Ryzen 9 3900X',
 'AMD Ryzen 9 6900HX',
 'AMD Ryzen 9 7900X',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 9 9900X',
 'AMD Ryzen 9 9900X3D',
 'AMD Ryzen 9 9950X',
 'AMD Ryzen 9 9950X3D',
 'Intel 12600H',
 'Intel 14450HX',
 'Intel G5905',
 'Intel Ultra 5',
 'Intel Ultra 7',
 'Intel Ultra 7 265F',
 'Intel Ultra 7 265K',
 'Intel Ultra 7 265KF',
 'Intel Ultra 9',
 'Intel Ultra 9 285K',
 'Intel Ultra 9 286K',
 'Intel Xeon E5',
 'Intel i3',
 'Intel i3 10100',
 'Intel i3 10100F',
 'Intel i3 10105',
 'Intel i5',
 'Intel i5 10400F',
 'Intel i5 10500',
 'Intel i5 11400F',
 'Intel i5 11600KF',
 'Intel i5 12400F',
 'Intel i5 13400F',
 'Intel i5 14400F',
 'Intel i5 6500',
 'Intel i5 7500',
 'Intel i5 8500',
 'Intel i5 9400F',
 'Intel i7',
 'Intel i7 10700K',
 'Intel i7 10700KF',
 'Intel i7 11700',
 'Intel i7 12700H',
 'Intel i7 13700F',
 'Intel i7 13700KF',
 'Intel i7 14700F',
 'Intel i7 14700K',
 'Intel i7 14700KF',
 'Intel i7 6700',
 'Intel i7 9700K',
 'Intel i7 Xeon',
 'Intel i9',
 'Intel i9 12900F',
 'Intel i9 12900KF',
 'Intel i9 13900F',
 'Intel i9 13900KF',
 'Intel i9 14900K',
 'Intel i9 14900KF',
 'Intel i9 9900K']

In [110]:
df_checkpoint = df_unfinishedv2.copy()
df_current = df_unfinishedv2.copy()

In [111]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,RTX5060,32GB DDR4,"8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME",Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,GeForce RTX 3050,6GB -16GB DDR4,6GB -16GB DDR4 3200MHz- 1TB M.2,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated Radeon,16GB 3200MHz DDR4,"5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB ...",Windows 10
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,"8GB, 16GB DDR4, 500GB SSD",Win 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA GeForce RTX 5060,16GB DDR5,16GB DDR5 RGB RAM 1TB Gen 4 SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,Geforce RTX 5090,64GB DDR5,"64GB DDR5, 2TB M.2",Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,0.0,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,GeForce RTX 5060,32GB Memory,"32GB Memory, 1TB SSD",Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA GeForce RTX 5060 Ti,16GB Memory,16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB ...,Win 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,9060XT,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11

In [112]:
len(df_current[df_current['Rating'] == 0.0])

47

In [113]:
df_current.dtypes

Title            object
Rating          float64
Rating Count      Int64
Price           float64
URL              object
Site             object
CPU              object
GPU              object
RAM              object
Storage          object
OS               object
dtype: object

In [114]:
df_current['Rating'] = df_current['Rating'].replace(0.0, df_current['Rating'].median())

In [115]:
len(df_current[df_current['Rating'] == 0.0])

0

In [116]:
df_current['GPU'].value_counts().sort_index().index.tolist()

['9060XT',
 'AMD RX 550',
 'AMD RX 580',
 'AMD RX 9060 XT',
 'AMD RX 9060XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD RX 9070XT',
 'AMD Radeon 780',
 'AMD Radeon RX 5500',
 'AMD Radeon RX 580',
 'AMD Radeon RX 9070XT',
 'GT 1030',
 'GTX 1050Ti',
 'GeForce GT 1030',
 'GeForce GTX 1050 Ti',
 'GeForce GTX 1660 Super',
 'GeForce GTX 1660 Ti',
 'GeForce GTX 750 Ti',
 'GeForce GTX1650',
 'GeForce RTX 2060',
 'GeForce RTX 3050',
 'GeForce RTX 3060',
 'GeForce RTX 3090',
 'GeForce RTX 4060',
 'GeForce RTX 4060 Ti',
 'GeForce RTX 4070',
 'GeForce RTX 4070 Super',
 'GeForce RTX 4070 Ti',
 'GeForce RTX 4090',
 'GeForce RTX 5060',
 'GeForce RTX 5060 Ti',
 'GeForce RTX 5070',
 'GeForce RTX 5070 Ti',
 'GeForce RTX 5080',
 'GeForce RTX 5090',
 'Geforce RTX 4070 Super',
 'Geforce RTX 5060',
 'Geforce RTX 5070Ti',
 'Geforce RTX 5090',
 'Integrated',
 'Integrated Radeon',
 'Intel® Arc™ B580',
 'NVIDIA GT 1030',
 'NVIDIA GeForce GTX 1650',
 'NVIDIA GeForce GTX 1650 SUPER',
 'NVIDIA GeForce GTX 1660',
 'NVIDIA GeForce RTX 2080 SUPER',
 'NVIDIA GeForce RTX 3070',
 'NVIDIA GeForce RTX 4060',
 'NVIDIA GeForce RTX 4070',
 'NVIDIA GeForce RTX 4070 Super',
 'NVIDIA GeForce RTX 4080',
 'NVIDIA GeForce RTX 4080 Super',
 'NVIDIA GeForce RTX 5060',
 'NVIDIA GeForce RTX 5060 Ti',
 'NVIDIA GeForce RTX 5060Ti',
 'NVIDIA GeForce RTX 5070',
 'NVIDIA GeForce RTX 5070Ti',
 'NVIDIA GeForce RTX 5080',
 'NVIDIA GeForce® RTX 5060',
 'NVIDIA GeForce® RTX 5070',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090',
 'NVIDIA® GeForce RTX™ 4060',
 'NVIDIA® GeForce RTX™ 4070 Ti',
 'NVIDIA® GeForce RTX™ 5060 Ti',
 'NVIDIA® GeForce RTX™ 5070',
 'NVIDIA® GeForce RTX™ 5070 Ti',
 'NVIDIA® GeForce RTX™ 5080',
 'NVIDIA® GeForce RTX™ 5090',
 'RTX 3050',
 'RTX 3060',
 'RTX 3070',
 'RTX 3080',
 'RTX 4070 Super',
 'RTX 5050',
 'RTX 5060',
 'RTX 5070',
 'RTX 5070 Ti',
 'RTX 5080',
 'RTX 5090',
 'RTX3050',
 'RTX5060',
 'RX 550',
 'RX 560',
 'RX 590',
 'Radeon 680',
 'Radeon 780',
 'Radeon 8060',
 'Radeon RX 550',
 'Radeon RX 560',
 'Radeon RX 5700 XT',
 'Radeon RX 5700XT',
 'Radeon RX 580',
 'Radeon RX 590',
 'Radeon RX 6400',
 'Radeon RX 6500',
 'Radeon RX 6500XT',
 'Vega 11',
 'Vega 7',
 'Vega 8',
 'Vega Graphics']

In [117]:
df_current['GPU'] = df_current['GPU'].str.replace('®', '')
df_current['GPU'] = df_current['GPU'].str.replace('™', '')
df_current['GPU'] = df_current['GPU'].str.replace('Radeon', '')
df_current['GPU'] = df_current['GPU'].str.replace('GeForce', '')

In [118]:
df_current['GPU'].value_counts().sort_index().index.tolist()

[' 680',
 ' 780',
 ' 8060',
 ' GT 1030',
 ' GTX 1050 Ti',
 ' GTX 1660 Super',
 ' GTX 1660 Ti',
 ' GTX 750 Ti',
 ' GTX1650',
 ' RTX 2060',
 ' RTX 3050',
 ' RTX 3060',
 ' RTX 3090',
 ' RTX 4060',
 ' RTX 4060 Ti',
 ' RTX 4070',
 ' RTX 4070 Super',
 ' RTX 4070 Ti',
 ' RTX 4090',
 ' RTX 5060',
 ' RTX 5060 Ti',
 ' RTX 5070',
 ' RTX 5070 Ti',
 ' RTX 5080',
 ' RTX 5090',
 ' RX 550',
 ' RX 560',
 ' RX 5700 XT',
 ' RX 5700XT',
 ' RX 580',
 ' RX 590',
 ' RX 6400',
 ' RX 6500',
 ' RX 6500XT',
 '9060XT',
 'AMD  780',
 'AMD  RX 5500',
 'AMD  RX 580',
 'AMD  RX 9070XT',
 'AMD RX 550',
 'AMD RX 580',
 'AMD RX 9060 XT',
 'AMD RX 9060XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD RX 9070XT',
 'GT 1030',
 'GTX 1050Ti',
 'Geforce RTX 4070 Super',
 'Geforce RTX 5060',
 'Geforce RTX 5070Ti',
 'Geforce RTX 5090',
 'Integrated',
 'Integrated ',
 'Intel Arc B580',
 'NVIDIA  GTX 1650',
 'NVIDIA  GTX 1650 SUPER',
 'NVIDIA  GTX 1660',
 'NVIDIA  RTX 2080 SUPER',
 'NVIDIA  RTX 3070',
 'NVIDIA  RTX 4060',
 'NVIDIA  RTX 4070',
 'NVIDIA  RTX 4070 Super',
 'NVIDIA  RTX 4070 Ti',
 'NVIDIA  RTX 4080',
 'NVIDIA  RTX 4080 Super',
 'NVIDIA  RTX 5060',
 'NVIDIA  RTX 5060 Ti',
 'NVIDIA  RTX 5060Ti',
 'NVIDIA  RTX 5070',
 'NVIDIA  RTX 5070 Ti',
 'NVIDIA  RTX 5070Ti',
 'NVIDIA  RTX 5080',
 'NVIDIA  RTX 5090',
 'NVIDIA GT 1030',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090',
 'RTX 3050',
 'RTX 3060',
 'RTX 3070',
 'RTX 3080',
 'RTX 4070 Super',
 'RTX 5050',
 'RTX 5060',
 'RTX 5070',
 'RTX 5070 Ti',
 'RTX 5080',
 'RTX 5090',
 'RTX3050',
 'RTX5060',
 'RX 550',
 'RX 560',
 'RX 590',
 'Vega 11',
 'Vega 7',
 'Vega 8',
 'Vega Graphics']

In [119]:
df_current['GPU'] = df_current['GPU'].str.replace(' 680', 'RX 680', regex = False)
df_current['GPU'] = df_current['GPU'].str.replace(' 780', 'RX 780', regex = False)
df_current['GPU'] = df_current['GPU'].str.replace(' 8060', 'RX 8060', regex = False)
df_current['GPU'] = df_current['GPU'].str.replace('9060XT', 'RX 9060 XT', regex = False)

df_current['GPU'] = np.where(
    ((df_current['GPU'].str.contains('RTX', case = False, na = False)) | 
    (df_current['GPU'].str.contains('GTX', case = False, na = False)) | 
    (df_current['GPU'].str.contains('GT', case = False, na = False))) & 
    ~df_current['GPU'].str.contains('NVIDIA', case = False, na = False),
    'NVIDIA ' + df_current['GPU'],
    df_current['GPU']
)

df_current['GPU'] = np.where(
    (df_current['GPU'].str.contains('RX', case = False, na = False) | 
     df_current['GPU'].str.contains('Vega', case = False, na = False)) & 
    ~df_current['GPU'].str.contains('AMD', case = False, na = False),
    'AMD ' + df_current['GPU'],
    df_current['GPU']
)

In [120]:
df_current['GPU'].value_counts().sort_index().index.tolist()

['AMD  RX 550',
 'AMD  RX 5500',
 'AMD  RX 560',
 'AMD  RX 5700 XT',
 'AMD  RX 5700XT',
 'AMD  RX 580',
 'AMD  RX 590',
 'AMD  RX 6400',
 'AMD  RX 6500',
 'AMD  RX 6500XT',
 'AMD  RX 9070XT',
 'AMD RX 550',
 'AMD RX 560',
 'AMD RX 580',
 'AMD RX 590',
 'AMD RX 680',
 'AMD RX 780',
 'AMD RX 8060',
 'AMD RX 9060 XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD RX 9070XT',
 'AMD RX RX 9060 XT',
 'AMD Vega 11',
 'AMD Vega 7',
 'AMD Vega 8',
 'AMD Vega Graphics',
 'Integrated',
 'Integrated ',
 'Intel Arc B580',
 'NVIDIA  GT 1030',
 'NVIDIA  GTX 1050 Ti',
 'NVIDIA  GTX 1650',
 'NVIDIA  GTX 1650 SUPER',
 'NVIDIA  GTX 1660',
 'NVIDIA  GTX 1660 Super',
 'NVIDIA  GTX 1660 Ti',
 'NVIDIA  GTX 750 Ti',
 'NVIDIA  GTX1650',
 'NVIDIA  RTX 2060',
 'NVIDIA  RTX 2080 SUPER',
 'NVIDIA  RTX 3050',
 'NVIDIA  RTX 3060',
 'NVIDIA  RTX 3070',
 'NVIDIA  RTX 3090',
 'NVIDIA  RTX 4060',
 'NVIDIA  RTX 4060 Ti',
 'NVIDIA  RTX 4070',
 'NVIDIA  RTX 4070 Super',
 'NVIDIA  RTX 4070 Ti',
 'NVIDIA  RTX 4080',
 'NVIDIA  RTX 4080 Super',
 'NVIDIA  RTX 4090',
 'NVIDIA  RTX 5060',
 'NVIDIA  RTX 5060 Ti',
 'NVIDIA  RTX 5060Ti',
 'NVIDIA  RTX 5070',
 'NVIDIA  RTX 5070 Ti',
 'NVIDIA  RTX 5070Ti',
 'NVIDIA  RTX 5080',
 'NVIDIA  RTX 5090',
 'NVIDIA GT 1030',
 'NVIDIA GTX 1050Ti',
 'NVIDIA Geforce RTX 4070 Super',
 'NVIDIA Geforce RTX 5060',
 'NVIDIA Geforce RTX 5070Ti',
 'NVIDIA Geforce RTX 5090',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 3060',
 'NVIDIA RTX 3070',
 'NVIDIA RTX 3080',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Super',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090',
 'NVIDIA RTX3050',
 'NVIDIA RTX5060']

In [121]:
df_current['GPU'] = df_current['GPU'].str.replace('Geforce', '')

In [122]:
df_current['GPU'].value_counts().sort_index().index.tolist()

['AMD  RX 550',
 'AMD  RX 5500',
 'AMD  RX 560',
 'AMD  RX 5700 XT',
 'AMD  RX 5700XT',
 'AMD  RX 580',
 'AMD  RX 590',
 'AMD  RX 6400',
 'AMD  RX 6500',
 'AMD  RX 6500XT',
 'AMD  RX 9070XT',
 'AMD RX 550',
 'AMD RX 560',
 'AMD RX 580',
 'AMD RX 590',
 'AMD RX 680',
 'AMD RX 780',
 'AMD RX 8060',
 'AMD RX 9060 XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD RX 9070XT',
 'AMD RX RX 9060 XT',
 'AMD Vega 11',
 'AMD Vega 7',
 'AMD Vega 8',
 'AMD Vega Graphics',
 'Integrated',
 'Integrated ',
 'Intel Arc B580',
 'NVIDIA  GT 1030',
 'NVIDIA  GTX 1050 Ti',
 'NVIDIA  GTX 1650',
 'NVIDIA  GTX 1650 SUPER',
 'NVIDIA  GTX 1660',
 'NVIDIA  GTX 1660 Super',
 'NVIDIA  GTX 1660 Ti',
 'NVIDIA  GTX 750 Ti',
 'NVIDIA  GTX1650',
 'NVIDIA  RTX 2060',
 'NVIDIA  RTX 2080 SUPER',
 'NVIDIA  RTX 3050',
 'NVIDIA  RTX 3060',
 'NVIDIA  RTX 3070',
 'NVIDIA  RTX 3090',
 'NVIDIA  RTX 4060',
 'NVIDIA  RTX 4060 Ti',
 'NVIDIA  RTX 4070',
 'NVIDIA  RTX 4070 Super',
 'NVIDIA  RTX 4070 Ti',
 'NVIDIA  RTX 4080',
 'NVIDIA  RTX 4080 Super',
 'NVIDIA  RTX 4090',
 'NVIDIA  RTX 5060',
 'NVIDIA  RTX 5060 Ti',
 'NVIDIA  RTX 5060Ti',
 'NVIDIA  RTX 5070',
 'NVIDIA  RTX 5070 Ti',
 'NVIDIA  RTX 5070Ti',
 'NVIDIA  RTX 5080',
 'NVIDIA  RTX 5090',
 'NVIDIA GT 1030',
 'NVIDIA GTX 1050Ti',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 3060',
 'NVIDIA RTX 3070',
 'NVIDIA RTX 3080',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Super',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090',
 'NVIDIA RTX3050',
 'NVIDIA RTX5060']

In [123]:
df_current['GPU'] = df_current['GPU'].str.replace('SUPER', 'Super', regex = False)
df_current["GPU"] = df_current["GPU"].str.replace(r"(?<! )XT", " XT", regex=True)
df_current["GPU"] = df_current["GPU"].str.replace(r"(?<! )Ti", " Ti", regex=True)
df_current['GPU'].value_counts().sort_index().index.tolist()

['AMD  RX 550',
 'AMD  RX 5500',
 'AMD  RX 560',
 'AMD  RX 5700 XT',
 'AMD  RX 580',
 'AMD  RX 590',
 'AMD  RX 6400',
 'AMD  RX 6500',
 'AMD  RX 6500 XT',
 'AMD  RX 9070 XT',
 'AMD RX 550',
 'AMD RX 560',
 'AMD RX 580',
 'AMD RX 590',
 'AMD RX 680',
 'AMD RX 780',
 'AMD RX 8060',
 'AMD RX 9060 XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD RX RX 9060 XT',
 'AMD Vega 11',
 'AMD Vega 7',
 'AMD Vega 8',
 'AMD Vega Graphics',
 'Integrated',
 'Integrated ',
 'Intel Arc B580',
 'NVIDIA  GT 1030',
 'NVIDIA  GTX 1050 Ti',
 'NVIDIA  GTX 1650',
 'NVIDIA  GTX 1650 Super',
 'NVIDIA  GTX 1660',
 'NVIDIA  GTX 1660 Super',
 'NVIDIA  GTX 1660 Ti',
 'NVIDIA  GTX 750 Ti',
 'NVIDIA  GTX1650',
 'NVIDIA  RTX 2060',
 'NVIDIA  RTX 2080 Super',
 'NVIDIA  RTX 3050',
 'NVIDIA  RTX 3060',
 'NVIDIA  RTX 3070',
 'NVIDIA  RTX 3090',
 'NVIDIA  RTX 4060',
 'NVIDIA  RTX 4060 Ti',
 'NVIDIA  RTX 4070',
 'NVIDIA  RTX 4070 Super',
 'NVIDIA  RTX 4070 Ti',
 'NVIDIA  RTX 4080',
 'NVIDIA  RTX 4080 Super',
 'NVIDIA  RTX 4090',
 'NVIDIA  RTX 5060',
 'NVIDIA  RTX 5060 Ti',
 'NVIDIA  RTX 5070',
 'NVIDIA  RTX 5070 Ti',
 'NVIDIA  RTX 5080',
 'NVIDIA  RTX 5090',
 'NVIDIA GT 1030',
 'NVIDIA GTX 1050 Ti',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 3060',
 'NVIDIA RTX 3070',
 'NVIDIA RTX 3080',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Super',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090',
 'NVIDIA RTX3050',
 'NVIDIA RTX5060']

In [124]:
df_current['GPU'] = df_current['GPU'].str.replace('NVIDIA RTX3050', 'NVIDIA RTX 3050', regex = False)
df_current['GPU'] = df_current['GPU'].str.replace('NVIDIA RTX5060', 'NVIDIA RTX 5060', regex = False)
df_current['GPU'] = df_current['GPU'].str.replace('NVIDIA  GTX1650', 'NVIDIA GTX 1650', regex = False)
df_current['GPU'].value_counts().sort_index().index.tolist()

['AMD  RX 550',
 'AMD  RX 5500',
 'AMD  RX 560',
 'AMD  RX 5700 XT',
 'AMD  RX 580',
 'AMD  RX 590',
 'AMD  RX 6400',
 'AMD  RX 6500',
 'AMD  RX 6500 XT',
 'AMD  RX 9070 XT',
 'AMD RX 550',
 'AMD RX 560',
 'AMD RX 580',
 'AMD RX 590',
 'AMD RX 680',
 'AMD RX 780',
 'AMD RX 8060',
 'AMD RX 9060 XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD RX RX 9060 XT',
 'AMD Vega 11',
 'AMD Vega 7',
 'AMD Vega 8',
 'AMD Vega Graphics',
 'Integrated',
 'Integrated ',
 'Intel Arc B580',
 'NVIDIA  GT 1030',
 'NVIDIA  GTX 1050 Ti',
 'NVIDIA  GTX 1650',
 'NVIDIA  GTX 1650 Super',
 'NVIDIA  GTX 1660',
 'NVIDIA  GTX 1660 Super',
 'NVIDIA  GTX 1660 Ti',
 'NVIDIA  GTX 750 Ti',
 'NVIDIA  RTX 2060',
 'NVIDIA  RTX 2080 Super',
 'NVIDIA  RTX 3050',
 'NVIDIA  RTX 3060',
 'NVIDIA  RTX 3070',
 'NVIDIA  RTX 3090',
 'NVIDIA  RTX 4060',
 'NVIDIA  RTX 4060 Ti',
 'NVIDIA  RTX 4070',
 'NVIDIA  RTX 4070 Super',
 'NVIDIA  RTX 4070 Ti',
 'NVIDIA  RTX 4080',
 'NVIDIA  RTX 4080 Super',
 'NVIDIA  RTX 4090',
 'NVIDIA  RTX 5060',
 'NVIDIA  RTX 5060 Ti',
 'NVIDIA  RTX 5070',
 'NVIDIA  RTX 5070 Ti',
 'NVIDIA  RTX 5080',
 'NVIDIA  RTX 5090',
 'NVIDIA GT 1030',
 'NVIDIA GTX 1050 Ti',
 'NVIDIA GTX 1650',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 3060',
 'NVIDIA RTX 3070',
 'NVIDIA RTX 3080',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Super',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090']

In [125]:
df_current['GPU'] = df_current['GPU'].str.replace('  ', ' ', regex = False)
df_current['GPU'] = df_current['GPU'].str.strip()
df_current['GPU'].value_counts().sort_index().index.tolist()

['AMD RX 550',
 'AMD RX 5500',
 'AMD RX 560',
 'AMD RX 5700 XT',
 'AMD RX 580',
 'AMD RX 590',
 'AMD RX 6400',
 'AMD RX 6500',
 'AMD RX 6500 XT',
 'AMD RX 680',
 'AMD RX 780',
 'AMD RX 8060',
 'AMD RX 9060 XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD RX RX 9060 XT',
 'AMD Vega 11',
 'AMD Vega 7',
 'AMD Vega 8',
 'AMD Vega Graphics',
 'Integrated',
 'Intel Arc B580',
 'NVIDIA GT 1030',
 'NVIDIA GTX 1050 Ti',
 'NVIDIA GTX 1650',
 'NVIDIA GTX 1650 Super',
 'NVIDIA GTX 1660',
 'NVIDIA GTX 1660 Super',
 'NVIDIA GTX 1660 Ti',
 'NVIDIA GTX 750 Ti',
 'NVIDIA RTX 2060',
 'NVIDIA RTX 2080 Super',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 3060',
 'NVIDIA RTX 3070',
 'NVIDIA RTX 3080',
 'NVIDIA RTX 3090',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Super',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 4090',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090']

In [126]:
df_current['GPU'] = df_current['GPU'].str.replace('AMD RX RX 9060 XT', 'AMD RX 9060 XT', regex = False)
df_current['GPU'].value_counts().sort_index().index.tolist()

['AMD RX 550',
 'AMD RX 5500',
 'AMD RX 560',
 'AMD RX 5700 XT',
 'AMD RX 580',
 'AMD RX 590',
 'AMD RX 6400',
 'AMD RX 6500',
 'AMD RX 6500 XT',
 'AMD RX 680',
 'AMD RX 780',
 'AMD RX 8060',
 'AMD RX 9060 XT',
 'AMD RX 9070',
 'AMD RX 9070 XT',
 'AMD Vega 11',
 'AMD Vega 7',
 'AMD Vega 8',
 'AMD Vega Graphics',
 'Integrated',
 'Intel Arc B580',
 'NVIDIA GT 1030',
 'NVIDIA GTX 1050 Ti',
 'NVIDIA GTX 1650',
 'NVIDIA GTX 1650 Super',
 'NVIDIA GTX 1660',
 'NVIDIA GTX 1660 Super',
 'NVIDIA GTX 1660 Ti',
 'NVIDIA GTX 750 Ti',
 'NVIDIA RTX 2060',
 'NVIDIA RTX 2080 Super',
 'NVIDIA RTX 3050',
 'NVIDIA RTX 3060',
 'NVIDIA RTX 3070',
 'NVIDIA RTX 3080',
 'NVIDIA RTX 3090',
 'NVIDIA RTX 4060',
 'NVIDIA RTX 4060 Ti',
 'NVIDIA RTX 4070',
 'NVIDIA RTX 4070 Super',
 'NVIDIA RTX 4070 Ti',
 'NVIDIA RTX 4080',
 'NVIDIA RTX 4080 Super',
 'NVIDIA RTX 4090',
 'NVIDIA RTX 5050',
 'NVIDIA RTX 5060',
 'NVIDIA RTX 5060 Ti',
 'NVIDIA RTX 5070',
 'NVIDIA RTX 5070 Ti',
 'NVIDIA RTX 5080',
 'NVIDIA RTX 5090']

In [127]:
df_checkpoint = df_current.copy()

In [128]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,"8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME",Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NVIDIA RTX 3050,6GB -16GB DDR4,6GB -16GB DDR4 3200MHz- 1TB M.2,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated,16GB 3200MHz DDR4,"5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB ...",Windows 10
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,"8GB, 16GB DDR4, 500GB SSD",Win 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,16GB DDR5 RGB RAM 1TB Gen 4 SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,"64GB DDR5, 2TB M.2",Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,4.1,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB Memory,"32GB Memory, 1TB SSD",Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB Memory,16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB ...,Win 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,AMD RX 9060 XT,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11

In [129]:
df_current['RAM'].value_counts().sort_index().index.tolist()

['128GB DDR5',
 '128GB LPDDR5',
 '12GB VRAM',
 '16 GB Memory',
 '16 GB RAM',
 '16G DDR4',
 '16G Memory',
 '16G RAM',
 '16GB 3200 MHz DDR4',
 '16GB 3200MHz DDR4',
 '16GB 3600Mhz DDR4',
 '16GB DDR3',
 '16GB DDR4',
 '16GB DDR5',
 '16GB DRAM',
 '16GB LPDDR5',
 '16GB Memory',
 '16GB RAM',
 '16GB RGB Memory',
 '16GB Ram',
 '16GB VRAM',
 '16gb RAM',
 '1GHz) 32GB DDR5',
 '2 GHz 8GB RAM',
 '2GHz - 16GB RAM',
 '32 GB Memory',
 '32 GB RAM',
 '32G DDR4',
 '32GB (2x16GB) DDR5',
 '32GB (2x16GB) RAM',
 '32GB 5600MT/s DDR5',
 '32GB 6000MT/s DDR5',
 '32GB ARGB RAM',
 '32GB Corsair Vengeance RGB DDR5',
 '32GB DDR4',
 '32GB DDR5',
 '32GB Dominator Titanium RGB DDR5',
 '32GB LPDDR5X',
 '32GB Memory',
 '32GB RAM',
 '32GB Vengeance RGB DDR5',
 '5060 GDDR6',
 '5600GT 3.9GHz 16GB(8G*2) DDR4',
 '5700G RAM',
 '5GHz - 16GB RAM',
 '5GHz) 16GB RAM',
 '64GB DDR4',
 '64GB DDR5',
 '64GB Dominator Titanium RGB DDR5',
 '64GB RAM',
 '6GB -16GB DDR4',
 '6GHz) 16GB DDR4',
 '8 GB DDR4',
 '8 GB RAM',
 '8GB DDR4',
 '8GB VRAM',
 '96GB DDR5',
 'Ram 16GB DDR4',
 'Ram 16GB DDR5',
 'Ram 32GB DDR5']

In [130]:
df_current['RAM'] = df_current['RAM'].str.replace('Ram', '')
df_current['RAM'] = df_current['RAM'].str.replace('RAM', '')
df_current['RAM'] = df_current['RAM'].str.replace('VRAM', '')
df_current['RAM'] = df_current['RAM'].str.replace('6GHz', '')
df_current['RAM'] = df_current['RAM'].str.replace('5GHz', '')
df_current['RAM'] = df_current['RAM'].str.replace(')', '')
df_current['RAM'] = df_current['RAM'].str.replace('Dominator Titanium RGB', '')
df_current['RAM'] = df_current['RAM'].str.replace('Memory', '')

In [131]:
df_current['RAM'].value_counts().sort_index().index.tolist()

[' - 16GB ',
 ' 16GB ',
 ' 16GB DDR4',
 ' 16GB DDR5',
 ' 32GB DDR5',
 '128GB DDR5',
 '128GB LPDDR5',
 '12GB V',
 '16 GB ',
 '16G ',
 '16G DDR4',
 '16GB ',
 '16GB 3200 MHz DDR4',
 '16GB 3200MHz DDR4',
 '16GB 3600Mhz DDR4',
 '16GB D',
 '16GB DDR3',
 '16GB DDR4',
 '16GB DDR5',
 '16GB LPDDR5',
 '16GB RGB ',
 '16GB V',
 '16gb ',
 '1GHz 32GB DDR5',
 '2 GHz 8GB ',
 '2GHz - 16GB ',
 '32 GB ',
 '32G DDR4',
 '32GB ',
 '32GB  DDR5',
 '32GB (2x16GB ',
 '32GB (2x16GB DDR5',
 '32GB 5600MT/s DDR5',
 '32GB 6000MT/s DDR5',
 '32GB ARGB ',
 '32GB Corsair Vengeance RGB DDR5',
 '32GB DDR4',
 '32GB DDR5',
 '32GB LPDDR5X',
 '32GB Vengeance RGB DDR5',
 '5060 GDDR6',
 '5600GT 3.9GHz 16GB(8G*2 DDR4',
 '5700G ',
 '64GB ',
 '64GB  DDR5',
 '64GB DDR4',
 '64GB DDR5',
 '6GB -16GB DDR4',
 '8 GB ',
 '8 GB DDR4',
 '8GB DDR4',
 '8GB V',
 '96GB DDR5']

In [132]:
def parse_ram(s):
    gb_match = re.search(r'(\d+)\s*GB?(?!\w)', s, re.IGNORECASE)
    ddr_match = re.search(r'DDR[3-9]', s, re.IGNORECASE)
    
    gb = gb_match.group(1) if gb_match else None
    ddr = ddr_match.group(0).upper() if ddr_match else None
    
    if gb and ddr:
        return f"{gb}GB {ddr}"
    elif gb:
        return f"{gb}GB"
    return None

In [133]:
df_current['RAM_Clean'] = df_current['RAM'].apply(parse_ram)

In [134]:
df_current['RAM_Clean'].value_counts().sort_index()

RAM_Clean
128GB DDR5      3
12GB            3
16GB           53
16GB DDR3       1
16GB DDR4      70
16GB DDR5      45
32GB           18
32GB DDR4      12
32GB DDR5     138
5700GB          1
64GB            4
64GB DDR4       1
64GB DDR5      34
6GB DDR4        1
8GB             6
8GB DDR4        4
96GB DDR5       2
Name: count, dtype: int64

In [135]:
df_current[df_current['RAM_Clean'] == '5700GB']['Title']

2932    PC Gaming Desktop AMD Ryzen 7 5700G RAM 16G 32...
Name: Title, dtype: object

In [136]:
df_current.loc[2932, 'RAM_Clean'] = '16GB DDR4'

In [137]:
df_current['RAM_Clean'].value_counts().sort_index()

RAM_Clean
128GB DDR5      3
12GB            3
16GB           53
16GB DDR3       1
16GB DDR4      71
16GB DDR5      45
32GB           18
32GB DDR4      12
32GB DDR5     138
64GB            4
64GB DDR4       1
64GB DDR5      34
6GB DDR4        1
8GB             6
8GB DDR4        4
96GB DDR5       2
Name: count, dtype: int64

In [138]:
df_current[df_current['RAM_Clean'] == '6GB DDR4']['Title']

8    Hoengager Gaming PC -Intel i5 13400F -GeForce ...
Name: Title, dtype: object

In [139]:
df_current.loc[8, 'RAM_Clean'] = '16GB DDR4'

In [140]:
df_current['RAM_Clean'].value_counts().sort_index().index.tolist()

['128GB DDR5',
 '12GB',
 '16GB',
 '16GB DDR3',
 '16GB DDR4',
 '16GB DDR5',
 '32GB',
 '32GB DDR4',
 '32GB DDR5',
 '64GB',
 '64GB DDR4',
 '64GB DDR5',
 '8GB',
 '8GB DDR4',
 '96GB DDR5']

In [141]:
df_current[df_current['RAM_Clean'] == '128GB DDR5']['Title'].tolist()

['ASUS ROG Strix G700 Desktop 11TB Storage + SSD 128GB DDR5 RAM Win 11 Pro (Intel 15th gen Core Ultra 9 Processor Turbo Boost to 6.00GHz, NVIDIA GeForce 4060Ti RTX 8GB GDDR6) Gaming PC Computer G700TF',
 'NIMO Mini PC Desktop, AMD Ryzen AI Max+ 395 128GB LPDDR5 8000MHz RAM 2TB SSD (Up to 5.1GHz) AI Server Radeon 8060S Graphics Computers with USB4.0 BT5.2 4K Display WiFi 7',
 'NIMO Mini PC Desktop, AMD Ryzen AI Max+ 395 128GB LPDDR5 8000MHz RAM 8TB SSD (Up to 5.1GHz) Mini Desktop Radeon 8060S 4K Display Graphics Computers with USB4.0 BT5.2 WiFi 7']

In [142]:
df_current['RAM_Clean'] = np.where(
    ~df_current['RAM_Clean'].str.contains('DDR4', case = False, na = False) &
    ~df_current['RAM_Clean'].str.contains('DDR5', case = False, na = False),
    df_current['RAM_Clean'] + ' DDR4',
    df_current['RAM_Clean']
)

In [143]:
df_current['RAM_Clean'].value_counts().sort_index().index.tolist()

['128GB DDR5',
 '12GB DDR4',
 '16GB DDR3 DDR4',
 '16GB DDR4',
 '16GB DDR5',
 '32GB DDR4',
 '32GB DDR5',
 '64GB DDR4',
 '64GB DDR5',
 '8GB DDR4',
 '96GB DDR5']

In [144]:
df_current['RAM_Clean'] = df_current['RAM_Clean'].str.replace('16GB DDR3 DDR4', '16GB DDR3', regex = False)

In [145]:
df_current['RAM_Clean'].value_counts(ascending = False)

RAM_Clean
32GB DDR5     138
16GB DDR4     125
16GB DDR5      45
64GB DDR5      34
32GB DDR4      30
8GB DDR4       10
64GB DDR4       5
12GB DDR4       3
128GB DDR5      3
96GB DDR5       2
16GB DDR3       1
Name: count, dtype: int64

In [146]:
df_checkpoint = df_current.copy()

In [147]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS,RAM_Clean
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,"8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME",Windows 11,32GB DDR4
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NVIDIA RTX 3050,6GB -16GB DDR4,6GB -16GB DDR4 3200MHz- 1TB M.2,Windows 11,16GB DDR4
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated,16GB 3200MHz DDR4,"5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB ...",Windows 10,16GB DDR4
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,"8GB, 16GB DDR4, 500GB SSD",Win 11 Pro,16GB DDR4
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,16GB DDR5 RGB RAM 1TB Gen 4 SSD,Windows 11 Home,16GB DDR5
...,...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,"64GB DDR5, 2TB M.2",Windows 11 Pro,64GB DDR5
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11,16GB DDR4
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,4.1,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB,"32GB Memory, 1TB SSD",Windows 11,32GB DDR4
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB,16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB ...,Win 11,16GB DDR4
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,AMD RX 9060 XT,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11,16GB DDR4

In [148]:
df_current['Storage'].value_counts().sort_index().index.tolist()

['10GB, 16GB DDR4, 1TB Gen4 SSD',
 '11TB Storage',
 '128GB LPDDR5 8000MHz RAM 2TB SSD',
 '128GB LPDDR5 8000MHz RAM 8TB SSD',
 '12GB & B760I AORUS PRO | 32GB DDR5 6000MHz | 1TB Gen4 M.2',
 '12GB GDDR7 | 32GB DDR5 RGB 6000MHz | 2TB Gen4 NVMe',
 '12GB GDDR7, 1TB Gen4 NVMe',
 '12GB GDDR7, 1TB Gen4 SSD',
 '12GB GDDR7, AMD Ryzen 7 7700X (Up to 5.4GHz), 64GB DDR5 5600MT/s, 4TB SSD',
 '12GB GPU, 32GB DDR5 RGB 5200MHz RAM, 1TB NVMe',
 '12GB VRAM, 1TB Gen4 NVMe',
 '12GB VRAM, 2TB Gen4 NVMe',
 '12GB, 16GB DDR4, 1TB NVMe',
 '12GB, 16GB DDR4, 500GB PCI-E NVMe',
 '12GB, 16GB DDR5, 1TB NVMe',
 '12GB, 1TB Gen4 NVMe',
 '12GB, 1TB NVMe',
 '12GB, 2TB Gen4 NVMe',
 '12GB, 32GB DDR4 3200, 1TB NVMe',
 '12GB, 32GB DDR5, 1TB PCIe 4.0 SSD',
 '16 GB Memory – 1 TB Storage',
 '16 GB RAM, 1 TB SSD',
 '16 GB RAM, 512 GB SSD',
 '16G DDR4, 1T SSD',
 '16G Memory | 512G SSD',
 '16G RAM, 512G SSD',
 '16GB (>4090), Liquid Cooled AMD Ryzen 7 9800X3D, 32GB DDR5, 2TB PCIe SSD',
 '16GB (>4090), Liquid Cooled Intel i9-14900K, 64GB DDR5, 2TB PCIe SSD',
 '16GB 3600Mhz DDR4 ToughRAM RGB Memory, 1TB NVMe',
 '16GB DDR3 RAM | 512GB SSD',
 '16GB DDR4 1TB PCIe 3.0x4 SSD',
 '16GB DDR4 1TB PCIe SSD',
 '16GB DDR4 3200MHz 1TB NVMe',
 '16GB DDR4 3600Mhz RGB Memory, Intel® Arc™ B580, 1TB NVMe',
 '16GB DDR4 512GB M.2',
 '16GB DDR4 512GB SSD',
 '16GB DDR4 RAM 256GB M.2',
 '16GB DDR4 RAM 256GB SSD',
 '16GB DDR4 RAM 512GB SSD',
 '16GB DDR4 RAM | 1TB SSD',
 '16GB DDR4 RAM – 256GB SSD',
 '16GB DDR4 RAM, 1TB SSD',
 '16GB DDR4 RAM, 512GB NVMe',
 '16GB DDR4 Ram, 512GB NVMe',
 '16GB DDR4, 1TB PCIe SSD',
 '16GB DDR4, 256GB SSD',
 '16GB DDR5 6000MHz, NVME',
 '16GB DDR5 6000MT/s RGB Memory, NVIDIA GeForce® RTX 5060, 1TB NVMe',
 '16GB DDR5 RGB RAM 1TB Gen 4 SSD',
 '16GB DDR5 | 1TB PCIe Gen 4 SSD',
 '16GB DDR5, 1TB m.2',
 '16GB DDR5,1TB NVME',
 '16GB DRAM, 1TB HDD',
 '16GB GDDR6, 1TB Gen4 NVMe',
 '16GB GDDR6X, 2TB Gen4 SSD',
 '16GB GDDR7, Mirage S Desktop Computer VR & AI Ready, 32GB DDR5 6000MHz, 2TB NVMe',
 '16GB GPU, 32GB DDR5 RGB 5200MHz RAM, 2TB NVMe',
 '16GB LPDDR5 512GB PCle SSD',
 '16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB - 1TB NVMe',
 '16GB Memory, 1TB SSD',
 '16GB RAM + 500GB SSD',
 '16GB RAM - 512GB M.2',
 '16GB RAM 512GB M.2',
 '16GB RAM 512GB SSD',
 '16GB RAM New 1TB SSD',
 '16GB RAM(Not LPDDR)&1TB NVMe',
 '16GB RAM, 1TB M.2',
 '16GB RAM, 1TB SSD',
 '16GB RAM, 1TBNVMe SSD',
 '16GB RAM, 2TB HDD',
 '16GB RAM, 512GB SSD',
 '16GB RGB Memory, NVIDIA GeForce® RTX 5060, 1TB NVMe',
 '16GB Ram, 256GB SSD',
 '16GB VRAM, 1TB Gen4 NVMe',
 '16GB VRAM, 2TB Gen4 NVMe',
 '16GB VRAM, X670 Board, 1TB Gen4 NVMe',
 '16GB | 16GB RAM | 1TB NVMe',
 '16GB | 2TB NvMe',
 '16GB | Gigabyte B850 Gaming WF6 | 32GB DDR5 6000MHz | 2TB Gen4 M.2',
 '16GB | Gigabyte Z890I AORUS Ultra | 32GB DDR5 6000MHz | 2TB Gen4 M.2',
 '16GB(8G*2) DDR4 3200 1T NVME',
 '16GB, 16GB DDR5 RAM, 1TB NVMe',
 '16GB, 16GB DDR5, 1TB PCIe 4.0 SSD',
 '16GB, 16GB DDR5, 1TB PCIe Gen4 SSD',
 '16GB, 1TB Gen4 NVMe',
 '16GB, 1TB NVMe',
 '16GB, 2TB Gen4 NVMe',
 '16GB, 2TB NVMe',
 '16GB, X670 Board, 2TB Gen4 NVMe',
 '16GB, X670 Board, 2TB NVMe',
 '16GB, X870 Board, 2TB Gen4 NVMe',
 '16GB, X870 Board, 4TB Gen4 NVMe',
 '16GB, Z790 Board, 2TB Gen4 NVMe',
 '16GB, Z890 Board, 2TB Gen4 NVMe',
 '16GB, Z890 Board, 2TB NVMe',
 '16GB|32GB (2x16GB) DDR5 5600MHz|2TB M.2',
 '16T, 4.8GHz), 32GB RAM 1TB PCle4.0 SSD',
 '16T, Max 4.8GHz), GeForce GTX1650 4G GDDR5 RGB Lights Desktop Gaming Mini Computer, 16GB RAM 1TB NVMe',
 '16T, up to 4.5GHz) 16GB RAM 512GB SSD',
 '16gb RAM, 1TB HDD',
 '1TB Gen4 NVMe',
 '1TB M.2',
 '1TB NVME',
 '1TB NVMe',
 '1TB SSD',
 '2870T Gaming Desktop (Intel® Core™ Ultra 9 285K, ToughRam 32GB DDR5 6400MT/s RGB Memory, NVIDIA® GeForce RTX™ 5070 Ti, 2TB NVMe',
 '2G GDDR5, 16GB DDR4, 512G SSD',
 '2GB GDDR5, 16GB RAM, 512GB SSD',
 '2TB NVMe',
 '3.5G, Radeon RX 580 16G, 16GB DDR4, 1TB SSD',
 '3.5G, Radeon RX 580 8G, 16G DDR4, 512G SSD',
 '3.6G, Radeon RX 550, 16G RAM, 512G SSD',
 '3.9G, GeForce RTX 2060 6G, 16G DDR4, 512G SSD',
 '3.9G, Radeon RX 580 8G, 16GB RAM, 512GB SSD',
 '32 GB Memory – 1 TB Storage',
 '32 GB RAM, 2TB SSD',
 '32G DDR4 RAM, 1TB NVME',
 '32GB (>4090), Liquid Cooled Intel i9-14900K, 32GB DDR5, 2TB PCIe SSD',
 '32GB (>4090), Liquid Cooled Intel i9-14900K, 64GB DDR5, 2TB PCIe SSD',
 '32GB 5600MT/s DDR5 RGB Memory, NVIDIA® GeForce RTX™ 4060, 1TB NVMe',
 '32GB 6000MT/s DDR5 RGB Memory, NVIDIA GeForce® RTX 5070, 1TB NVMe',
 '32GB 6000MT/s DDR5 RGB Memory, NVIDIA® GeForce RTX™ 5090, 2TB NVMe',
 '32GB ARGB RAM, 512GB SSD',
 '32GB Corsair Vengeance RGB DDR5 Memory – 2TB M.2',
 '32GB DDR4 RAM and 1TB M.2',
 '32GB DDR4 RAM, 2TBNVMe SSD',
 '32GB DDR4, 1TB PCIe SSD',
 '32GB DDR5 (Upgradable, Not LPDDR) 512GB NVMe',
 '32GB DDR5 1TB PCle4.0 SSD',
 '32GB DDR5 1TB SSD',
 '32GB DDR5 2TB SSD',
 '32GB DDR5 6000MT/s RGB Memory, NVIDIA® GeForce RTX™ 5070, 1TB NVMe',
 '32GB DDR5 6000MT/s RGB Memory, NVIDIA® GeForce RTX™ 5090, 2TB NVMe',
 '32GB DDR5 6400MT/s RGB Memory, NVIDIA® GeForce RTX™ 5070 Ti, 2TB NVMe',
 '32GB DDR5 6400MT/s RGB Memory, NVIDIA® GeForce RTX™ 5080, 2TB NVMe',
 '32GB DDR5 Memory, GeForce RTX 4070 12GB GDDR6X Graphics, 1TB SSD',
 '32GB DDR5 RAM, 1TB NVMe',
 '32GB DDR5 RAM, 1TB SSD',
 '32GB DDR5 RAM, 2TB Gen4 NVMe',
 '32GB DDR5 RAM, 2TB Gen4 SSD',
 '32GB DDR5 RAM, 2TB Gen5 SSD',
 '32GB DDR5 RAM, 2TB NVMe',
 '32GB DDR5 RGB, 2TB NVME',
 '32GB DDR5(Upgradable),1TB NVMe',
 '32GB DDR5, 1TB PCIe SSD',
 '32GB DDR5, 1TB m.2',
 '32GB DDR5, 2TB M.2',
 '32GB DDR5, 2TB SSD',
 '32GB DDR5, 2TB m.2',
 '32GB DDR5, 512GB NVMe',
 '32GB DDR5, AMD Ryzen 5 9600X, RTX 5060 8G, 1TB PCIe SSD',
 '32GB Dominator Titanium RGB DDR5 Memory – 2TB M.2',
 '32GB LPDDR5X Mini Computers, 1TB PCIe4.0 NVMe',
 '32GB Memory, 1TB SSD',
 '32GB RAM + 1TB Solid State Drive SSD',
 '32GB RAM 1TB NVMe',
 '32GB RAM 1TB SSD',
 '32GB RAM 2TB SSD',
 '32GB RAM 512GB SSD',
 '32GB RAM, 1TBNVMe SSD',
 '32GB Vengeance RGB DDR5 Memory – 1TB M.2',
 '32GB Vengeance RGB DDR5 Memory – 2TB M.2',
 '32GB, 64GB DDR5, 4TB PCIe Gen4 SSD',
 '32GB, X870 Board, 2TB Gen4 NVMe',
 '32GB, X870 Board, 4TB Gen4 NVMe',
 '32GB, Z890 Board, 2TB Gen4 NVMe',
 '32GB, Z890 Board, 4TB Gen4 NVMe',
 '3400G, 4K Vega Graphics, 16GB RAM, 512GB M.2',
 '4.0G, Radeon RX 5700XT 8G, 16G DDR4, 1T SSD',
 '4.6G, Radeon RX 6500 4G, 16G DDR4, 1T SSD',
 '4G GDDR5, 16G RAM, 512GB NVME',
 '4G GDDR5, 16GB Memory, 512G SSD',
 '4G GDDR5, Intel Core i5 up to 3.6G, 16G RAM, 512G SSD',
 '4G, 16G RAM, 512GB NVME',
 '4G, 16GB DDR4, 512G SSD',
 '4G, 16GB RAM, 512GB SSD',
 '4G, Intel Core I7 8th up to 4.1GHz, 16G DDR4, 512G SSD',
 '4G, Intel Core i5 up to 3.6GHz, 16G RAM, 512G SSD',
 '4GB GDDR5, 32GB RAM, 512GB NVMe',
 '4GB, 16GB DDR4 RAM, 1TB NVME',
 '4GB, 16GB DDR4, 500GB PCIe Gen4 SSD',
 '500GB NVMe',
 '5300G Processor, 8 GB RAM, 256 GB SSD',
 '5300G Processor, 8 GB RAM, 512 GB SSD',
 '5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB 3200MHz DDR4, 1TB NVME',
 '5700G CPU (4.6GHz Turbo) | Radeon Vega 8 Graphics | 1TB M.2',
 '5700G RAM 16G 3200MHz DDR4 1TB M.2',
 '5700G up to 4.6G, 16GB DDR4, 1TB SSD',
 '5700G, 16GB DDR4 RAM, 512GB NVMe',
 '64GB DDR4, 1TB PCIe SSD',
 '64GB DDR5 2TB SSD',
 '64GB DDR5 RAM, 2TB Gen4 SSD',
 '64GB DDR5 RAM, 2TB NVMe',
 '64GB DDR5 RAM, 2TB SSD',
 '64GB DDR5 RAM, 4TB Gen4 SSD',
 '64GB DDR5 RAM, 8TB SSD',
 '64GB DDR5, 2TB M.2',
 '64GB DDR5-5600/1TB SSD',
 '64GB Dominator Titanium RGB DDR5 Memory, 2+4TB M.2',
 '64GB Dominator Titanium RGB DDR5 Memory, Windows 11 Pro – 2TBx2 M.2',
 '64GB RAM 4TB SSD',
 '64GB RAM || 5TB High Speed Storage',
 '64GB RAM, 1TB SSD',
 '64GB RAM, 4TB SSD',
 '6G, 16G DDR4, 512G SSD',
 '6G, Intel Core I7 up to 3.9GHz, 16G RAM, 512G SSD',
 '6G, Intel Core i3-10100F up to 4.3Ghz, 16G DDR4, 1T SSD',
 '6G,16G DDR4, 1T SSD',
 '6GB -16GB DDR4 3200MHz- 1TB M.2',
 '6GB | 16GB RAM | 1TB NVMe',
 '6GB) 6GB GDDR6, 1TB SSD',
 '6GB, 8GB DDR4, 240GB SSD',
 '6GB, 8GB DDR4, 500GB NVMe',
 '6GB,16GB DDR4 RAM,1TB NVMe',
 '6GB,32GB RAM and 1TB M.2',
 '8 GB DDR4 RAM, 256 GB PCIe NVMe',
 '8 GB RAM, 256 GB SSD',
 '8 GB, HyperX 32 GB RAM, 1 TB SSD',
 '8G GDDR5, AMD Ryzen 3 3200G 3.6G, 16G DDR4, 512G SSD',
 '8G, 16G RAM, 512G SSD',
 '8G, 32GB DDR5 RAM 6000MHz, 1TB PCIe SSD',
 '8GB DDR4, GeForce RTX 2060 6GB, 500GB NVMe',
 '8GB GDDR5 Video Memory,16GB RAM, 512GB SSD',
 '8GB GDDR5, AMD Ryzen 5 5500 up to 4.2GHz, 16G RAM, 512GB NVME',
 '8GB GDDR6, 1TB SSD',
 '8GB GDDR6X, 1TB SSD',
 '8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME',
 '8GB GDDR7, 32GB DDR5, 3TB Storage',
 '8GB GPU, 32GB DDR5 RGB 5200MHz RAM, 1TB NVMe',
 '8GB GPU, 32GB DDR5 RGB 5200MHz RAM, 1TB SSD',
 '8GB Graphics, 512 GB M.2',
 '8GB RAM 256GB SSD',
 '8GB VRAM, 1TB Gen4 NVMe',
 '8GB, 16GB DDR4 3000, 1TB NVME',
 '8GB, 16GB DDR4 3200, 1TB NVMe',
 '8GB, 16GB DDR4 RAM, 500GB SSD',
 '8GB, 16GB DDR4, 1TB NVMe',
 '8GB, 16GB DDR4, 500GB NVMe',
 '8GB, 16GB DDR4, 500GB SSD',
 '8GB, 16GB DDR5, 1TB PCIe 4.0 SSD',
 '8GB, 16GB DDR5, 1TB PCIe Gen4 SSD',
 '8GB, 16GB DDR5, 2TB PCIe 4.0 SSD',
 '8GB, 16GB DDR5, 500GB NVMe',
 '8GB, 1TB Gen4 NVMe',
 '8GB, 1TB NVMe',
 '8GB, 2TB NVMe',
 '8GB, 32GB DDR5 RAM, 1TB SSD',
 '8GB,16 GB RAM,512GB SSD']

In [149]:
def extract_storage_clean(text):
    # Remove frequencies, MHz, MT/s
    cleaned = re.sub(r'\d+(?:\.\d+)?\s*GHz', '', text, flags=re.IGNORECASE)
    cleaned = re.sub(r'\d+\s*MHz', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'\d+\s*MT/s', '', cleaned, flags=re.IGNORECASE)

    # Storage type: optional PCIe/Gen prefix + storage keyword
    storage_type = (
        r'(?:'
            r'(?:PCIe|PCle|PCI-E)\s*(?:Gen\s*\d+\s*)?(?:\d+(?:\.\d+)?x?\d*)?\s*'  # PCIe 4.0 / PCIe Gen4
            r'|(?:Gen\s*\d+\s*)'                                                      # standalone Gen4 / Gen 4
        r')?'
        r'(?:NVMe|NVME|M\.2|HDD|SSD|Storage|Solid\s*State\s*Drive)'
    )

    pattern = rf'(\d+(?:\.\d+)?)\s*(TB|GB|T|G)\s*x?\d*\s*({storage_type})'

    matches = re.findall(pattern, cleaned, re.IGNORECASE)

    unit_map = {'T': 'TB', 'G': 'GB', 'TB': 'TB', 'GB': 'GB'}

    results = []
    for size, unit, stype in matches:
        unit_clean = unit_map.get(unit.upper(), unit.upper())
        stype_clean = re.sub(r'\s+', ' ', stype.strip())
        results.append(f"{size}{unit_clean} {stype_clean}")

    # Fallback: standalone NVME with no adjacent size
    if not results and re.search(r'\bNVME\b', cleaned, re.IGNORECASE):
        size_match = re.search(r'(\d+)\s*(TB|GB|T|G)', cleaned, re.IGNORECASE)
        if size_match:
            size, unit = size_match.groups()
            unit_clean = unit_map.get(unit.upper(), unit.upper())
            results.append(f"{size}{unit_clean} NVMe")

    return results[-1] if results else None

In [150]:
df_current['Storage_Clean'] = df_current['Storage'].apply(extract_storage_clean)

In [151]:
df_current[df_current['Storage_Clean'].isna()]['Storage'].tolist()

['64GB RAM || 5TB High Speed Storage']

In [152]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB Storage',
 '16GB NVMe',
 '1TB Gen 4 SSD',
 '1TB Gen4 M.2',
 '1TB Gen4 NVMe',
 '1TB Gen4 SSD',
 '1TB HDD',
 '1TB M.2',
 '1TB NVME',
 '1TB NVMe',
 '1TB PCIe 3.0x4 SSD',
 '1TB PCIe 4.0 SSD',
 '1TB PCIe Gen 4 SSD',
 '1TB PCIe Gen4 SSD',
 '1TB PCIe SSD',
 '1TB PCIe4.0 NVMe',
 '1TB PCle4.0 SSD',
 '1TB SSD',
 '1TB Solid State Drive',
 '1TB Storage',
 '1TB m.2',
 '240GB SSD',
 '256GB M.2',
 '256GB PCIe NVMe',
 '256GB SSD',
 '2TB Gen4 M.2',
 '2TB Gen4 NVMe',
 '2TB Gen4 SSD',
 '2TB Gen5 SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVME',
 '2TB NVMe',
 '2TB NvMe',
 '2TB PCIe 4.0 SSD',
 '2TB PCIe SSD',
 '2TB SSD',
 '2TB m.2',
 '3TB Storage',
 '4TB Gen4 NVMe',
 '4TB Gen4 SSD',
 '4TB M.2',
 '4TB PCIe Gen4 SSD',
 '4TB SSD',
 '500GB NVMe',
 '500GB PCI-E NVMe',
 '500GB PCIe Gen4 SSD',
 '500GB SSD',
 '512GB M.2',
 '512GB NVME',
 '512GB NVMe',
 '512GB PCle SSD',
 '512GB SSD',
 '8TB SSD']

In [153]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('Gen4', '')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('Gen 4', '')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('Gen5', '')

df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('PCIe', '')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('PCI-E', '')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('PCIe4.0', '')

In [154]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB Storage',
 '16GB NVMe',
 '1TB   SSD',
 '1TB  3.0x4 SSD',
 '1TB  4.0 SSD',
 '1TB  M.2',
 '1TB  NVMe',
 '1TB  SSD',
 '1TB 4.0 NVMe',
 '1TB HDD',
 '1TB M.2',
 '1TB NVME',
 '1TB NVMe',
 '1TB PCle4.0 SSD',
 '1TB SSD',
 '1TB Solid State Drive',
 '1TB Storage',
 '1TB m.2',
 '240GB SSD',
 '256GB  NVMe',
 '256GB M.2',
 '256GB SSD',
 '2TB  4.0 SSD',
 '2TB  M.2',
 '2TB  NVMe',
 '2TB  SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVME',
 '2TB NVMe',
 '2TB NvMe',
 '2TB SSD',
 '2TB m.2',
 '3TB Storage',
 '4TB   SSD',
 '4TB  NVMe',
 '4TB  SSD',
 '4TB M.2',
 '4TB SSD',
 '500GB   SSD',
 '500GB  NVMe',
 '500GB NVMe',
 '500GB SSD',
 '512GB M.2',
 '512GB NVME',
 '512GB NVMe',
 '512GB PCle SSD',
 '512GB SSD',
 '8TB SSD']

In [155]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('PCle', '')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('4.0', '')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('3.0', '')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('x4', '')

In [156]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB Storage',
 '16GB NVMe',
 '1TB   SSD',
 '1TB  M.2',
 '1TB  NVMe',
 '1TB  SSD',
 '1TB HDD',
 '1TB M.2',
 '1TB NVME',
 '1TB NVMe',
 '1TB SSD',
 '1TB Solid State Drive',
 '1TB Storage',
 '1TB m.2',
 '240GB SSD',
 '256GB  NVMe',
 '256GB M.2',
 '256GB SSD',
 '2TB   SSD',
 '2TB  M.2',
 '2TB  NVMe',
 '2TB  SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVME',
 '2TB NVMe',
 '2TB NvMe',
 '2TB SSD',
 '2TB m.2',
 '3TB Storage',
 '4TB   SSD',
 '4TB  NVMe',
 '4TB  SSD',
 '4TB M.2',
 '4TB SSD',
 '500GB   SSD',
 '500GB  NVMe',
 '500GB NVMe',
 '500GB SSD',
 '512GB  SSD',
 '512GB M.2',
 '512GB NVME',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [157]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('Storage', 'SDD')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace(r'(?i)nvme', 'NVMe', regex = True)
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace(r'(?i)m.2', 'M.2')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('Solid State Driver', 'SSD')

In [158]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SDD',
 '16GB NVMe',
 '1TB   SSD',
 '1TB  M.2',
 '1TB  NVMe',
 '1TB  SSD',
 '1TB HDD',
 '1TB M.2',
 '1TB NVMe',
 '1TB SDD',
 '1TB SSD',
 '1TB Solid State Drive',
 '1TB m.2',
 '240GB SSD',
 '256GB  NVMe',
 '256GB M.2',
 '256GB SSD',
 '2TB   SSD',
 '2TB  M.2',
 '2TB  NVMe',
 '2TB  SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVMe',
 '2TB SSD',
 '2TB m.2',
 '3TB SDD',
 '4TB   SSD',
 '4TB  NVMe',
 '4TB  SSD',
 '4TB M.2',
 '4TB SSD',
 '500GB   SSD',
 '500GB  NVMe',
 '500GB NVMe',
 '500GB SSD',
 '512GB  SSD',
 '512GB M.2',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [159]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace(r'(?i)m.2', 'M.2')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('Solid State Drive', 'SSD')

In [160]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SDD',
 '16GB NVMe',
 '1TB   SSD',
 '1TB  M.2',
 '1TB  NVMe',
 '1TB  SSD',
 '1TB HDD',
 '1TB M.2',
 '1TB NVMe',
 '1TB SDD',
 '1TB SSD',
 '1TB m.2',
 '240GB SSD',
 '256GB  NVMe',
 '256GB M.2',
 '256GB SSD',
 '2TB   SSD',
 '2TB  M.2',
 '2TB  NVMe',
 '2TB  SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVMe',
 '2TB SSD',
 '2TB m.2',
 '3TB SDD',
 '4TB   SSD',
 '4TB  NVMe',
 '4TB  SSD',
 '4TB M.2',
 '4TB SSD',
 '500GB   SSD',
 '500GB  NVMe',
 '500GB NVMe',
 '500GB SSD',
 '512GB  SSD',
 '512GB M.2',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [161]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('m.2', 'M.2')

In [162]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SDD',
 '16GB NVMe',
 '1TB   SSD',
 '1TB  M.2',
 '1TB  NVMe',
 '1TB  SSD',
 '1TB HDD',
 '1TB M.2',
 '1TB NVMe',
 '1TB SDD',
 '1TB SSD',
 '240GB SSD',
 '256GB  NVMe',
 '256GB M.2',
 '256GB SSD',
 '2TB   SSD',
 '2TB  M.2',
 '2TB  NVMe',
 '2TB  SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVMe',
 '2TB SSD',
 '3TB SDD',
 '4TB   SSD',
 '4TB  NVMe',
 '4TB  SSD',
 '4TB M.2',
 '4TB SSD',
 '500GB   SSD',
 '500GB  NVMe',
 '500GB NVMe',
 '500GB SSD',
 '512GB  SSD',
 '512GB M.2',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [163]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('  ', ' ')
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.strip()

In [164]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SDD',
 '16GB NVMe',
 '1TB  SSD',
 '1TB HDD',
 '1TB M.2',
 '1TB NVMe',
 '1TB SDD',
 '1TB SSD',
 '240GB SSD',
 '256GB M.2',
 '256GB NVMe',
 '256GB SSD',
 '2TB  SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVMe',
 '2TB SSD',
 '3TB SDD',
 '4TB  SSD',
 '4TB M.2',
 '4TB NVMe',
 '4TB SSD',
 '500GB  SSD',
 '500GB NVMe',
 '500GB SSD',
 '512GB M.2',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [165]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('  ', ' ')

In [166]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SDD',
 '16GB NVMe',
 '1TB HDD',
 '1TB M.2',
 '1TB NVMe',
 '1TB SDD',
 '1TB SSD',
 '240GB SSD',
 '256GB M.2',
 '256GB NVMe',
 '256GB SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVMe',
 '2TB SSD',
 '3TB SDD',
 '4TB M.2',
 '4TB NVMe',
 '4TB SSD',
 '500GB NVMe',
 '500GB SSD',
 '512GB M.2',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [167]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('SDD', 'SSD')

In [168]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SSD',
 '16GB NVMe',
 '1TB HDD',
 '1TB M.2',
 '1TB NVMe',
 '1TB SSD',
 '240GB SSD',
 '256GB M.2',
 '256GB NVMe',
 '256GB SSD',
 '2TB HDD',
 '2TB M.2',
 '2TB NVMe',
 '2TB SSD',
 '3TB SSD',
 '4TB M.2',
 '4TB NVMe',
 '4TB SSD',
 '500GB NVMe',
 '500GB SSD',
 '512GB M.2',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [169]:
df_current[df_current['Storage_Clean'] == '16GB NVMe']['CPU'].tolist()

['AMD Ryzen 7 7700']

In [170]:
df_current[df_current['Storage_Clean'] == '16GB NVMe']['Title'].index

Index([17], dtype='int64')

In [171]:
df_current.loc[17, 'Storage_Clean'] = '1TB NVMe'

In [172]:
df_current[df_current['Storage_Clean'] == '256GB M.2']['Storage'].tolist()

['16GB DDR4 RAM 256GB M.2']

In [173]:
df_current['Storage_Clean'] = df_current['Storage_Clean'].str.replace('M.2', 'SSD')

In [174]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SSD',
 '1TB HDD',
 '1TB NVMe',
 '1TB SSD',
 '240GB SSD',
 '256GB NVMe',
 '256GB SSD',
 '2TB HDD',
 '2TB NVMe',
 '2TB SSD',
 '3TB SSD',
 '4TB NVMe',
 '4TB SSD',
 '500GB NVMe',
 '500GB SSD',
 '512GB NVMe',
 '512GB SSD',
 '8TB SSD']

In [175]:
df_checkpoint = df_current.copy()

In [176]:
df_current['OS'].value_counts().sort_index().index.tolist()

['W-11 Pro',
 'Win 10 Home',
 'Win 11',
 'Win 11 Home',
 'Win 11 Pro',
 'Win11',
 'Win11 Pro',
 'Win11Home',
 'Win11Pro',
 'Window 11 Home',
 'Windows 10',
 'Windows 10 Home',
 'Windows 10 Pro',
 'Windows 11',
 'Windows 11 Home',
 'Windows 11 PRO',
 'Windows 11 Pro']

In [177]:
df_current[df_current['Storage_Clean'].isna()]['Title'].tolist()

['The Horizon Autherium Dragon RGB I9 RTX Gaming PC || 64GB RAM || 5TB High Speed Storage || Core I9 Upto 5.4Ghz || RTX 5070 OC || Windows 11 PRO || 360MM AIO || 2.4GB/s WiFi 6E, VR and Gaming Ready']

In [178]:
df_current.loc[2931, 'Storage_Clean'] = '5TB SSD'

In [179]:
df_current['Storage_Clean'].value_counts().sort_index().index.tolist()

['11TB SSD',
 '1TB HDD',
 '1TB NVMe',
 '1TB SSD',
 '240GB SSD',
 '256GB NVMe',
 '256GB SSD',
 '2TB HDD',
 '2TB NVMe',
 '2TB SSD',
 '3TB SSD',
 '4TB NVMe',
 '4TB SSD',
 '500GB NVMe',
 '500GB SSD',
 '512GB NVMe',
 '512GB SSD',
 '5TB SSD',
 '8TB SSD']

In [180]:
df_checkpoint = df_current.copy()

In [181]:
df_current['OS'].value_counts().sort_index().index.tolist()

['W-11 Pro',
 'Win 10 Home',
 'Win 11',
 'Win 11 Home',
 'Win 11 Pro',
 'Win11',
 'Win11 Pro',
 'Win11Home',
 'Win11Pro',
 'Window 11 Home',
 'Windows 10',
 'Windows 10 Home',
 'Windows 10 Pro',
 'Windows 11',
 'Windows 11 Home',
 'Windows 11 PRO',
 'Windows 11 Pro']

In [182]:
def clean_os(row):
    if pd.isna(row):
        return None

    s = str(row).upper()
    if 'W-11' in s or 'WIN 11' in s or 'WINDOW 11' in s or 'WINDOWS 11' in s or 'WIN11' in s:
        if 'PRO' in s:
            return 'Windows 11 Pro'
        elif 'HOME' in s:
            return 'Windows 11 Home'
        else:
            return 'Windows 11'

    elif 'WINDOWS 10' in s or 'WIN 10' in s:
        if 'PRO':
            return 'Windows 10 Pro'
        elif 'HOME':
            return 'Windows 10 Home'
        else:
            return 'Windows 10'

    return None

In [183]:
df_current['OS_Clean'] = df_current['OS'].apply(clean_os)

In [184]:
df_current['OS_Clean'].value_counts().sort_index().index.tolist()

['Windows 10 Pro', 'Windows 11', 'Windows 11 Home', 'Windows 11 Pro']

In [185]:
df_current['OS_Clean'].value_counts()

OS_Clean
Windows 11         224
Windows 11 Home     90
Windows 11 Pro      70
Windows 10 Pro      13
Name: count, dtype: int64

In [186]:
df_current['OS_Clean'].isna().sum()

0

In [187]:
df_checkpoint = df_current.copy()

In [188]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS,RAM_Clean,Storage_Clean,OS_Clean
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,"8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME",Windows 11,32GB DDR4,1TB NVMe,Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NVIDIA RTX 3050,6GB -16GB DDR4,6GB -16GB DDR4 3200MHz- 1TB M.2,Windows 11,16GB DDR4,1TB SSD,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated,16GB 3200MHz DDR4,"5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB ...",Windows 10,16GB DDR4,1TB NVMe,Windows 10 Pro
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,"8GB, 16GB DDR4, 500GB SSD",Win 11 Pro,16GB DDR4,500GB SSD,Windows 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,16GB DDR5 RGB RAM 1TB Gen 4 SSD,Windows 11 Home,16GB DDR5,1TB SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,"64GB DDR5, 2TB M.2",Windows 11 Pro,64GB DDR5,2TB SSD,Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11,16GB DDR4,1TB NVMe,Windows 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,4.1,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB,"32GB Memory, 1TB SSD",Windows 11,32GB DDR4,1TB SSD,Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB,16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB ...,Win 11,16GB DDR4,1TB NVMe,Windows 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,AMD RX 9060 XT,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11,16GB DDR4,1TB NVMe,Windows 11

In [189]:
df_v1 = df_current.copy()

In [190]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS,RAM_Clean,Storage_Clean,OS_Clean
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,"8GB GDDR7 DLSS4,32GB DDR4 RAM 3200MHz,1TB NVME",Windows 11,32GB DDR4,1TB NVMe,Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NVIDIA RTX 3050,6GB -16GB DDR4,6GB -16GB DDR4 3200MHz- 1TB M.2,Windows 11,16GB DDR4,1TB SSD,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated,16GB 3200MHz DDR4,"5600G 3.9 GHz, Integrated Radeon Vega 7, 16GB ...",Windows 10,16GB DDR4,1TB NVMe,Windows 10 Pro
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,"8GB, 16GB DDR4, 500GB SSD",Win 11 Pro,16GB DDR4,500GB SSD,Windows 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,16GB DDR5 RGB RAM 1TB Gen 4 SSD,Windows 11 Home,16GB DDR5,1TB SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,"64GB DDR5, 2TB M.2",Windows 11 Pro,64GB DDR5,2TB SSD,Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11,16GB DDR4,1TB NVMe,Windows 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,4.1,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB,"32GB Memory, 1TB SSD",Windows 11,32GB DDR4,1TB SSD,Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB,16GB Memory - NVIDIA GeForce RTX 5060 Ti 16GB ...,Win 11,16GB DDR4,1TB NVMe,Windows 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,AMD RX 9060 XT,16GB 3200 MHz DDR4,"16GB, 1TB Gen4 NVMe",Win 11,16GB DDR4,1TB NVMe,Windows 11

In [191]:
df_current.drop(columns = ['RAM', 'Storage', 'OS'], inplace = True)

In [192]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM_Clean,Storage_Clean,OS_Clean
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,1TB NVMe,Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NVIDIA RTX 3050,16GB DDR4,1TB SSD,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated,16GB DDR4,1TB NVMe,Windows 10 Pro
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,500GB SSD,Windows 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,1TB SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,2TB SSD,Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB DDR4,1TB NVMe,Windows 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,4.1,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB DDR4,1TB SSD,Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB DDR4,1TB NVMe,Windows 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,AMD RX 9060 XT,16GB DDR4,1TB NVMe,Windows 11

In [193]:
df_current.rename(columns = {'RAM_Clean':'RAM', 'Storage_Clean':'Storage', 'OS_Clean':'OS'}, inplace = True)

In [194]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,1TB NVMe,Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NVIDIA RTX 3050,16GB DDR4,1TB SSD,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated,16GB DDR4,1TB NVMe,Windows 10 Pro
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,500GB SSD,Windows 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,1TB SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,2TB SSD,Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB DDR4,1TB NVMe,Windows 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,4.1,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB DDR4,1TB SSD,Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB DDR4,1TB NVMe,Windows 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,AMD RX 9060 XT,16GB DDR4,1TB NVMe,Windows 11

In [195]:
df_current['CPU'].value_counts().sort_index().index.tolist()

['AMD Ryzen 3 3200G',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 4300U',
 'AMD Ryzen 5',
 'AMD Ryzen 5 2600',
 'AMD Ryzen 5 3400G',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 5 5500U',
 'AMD Ryzen 5 5600',
 'AMD Ryzen 5 5600G',
 'AMD Ryzen 5 5600GT',
 'AMD Ryzen 5 5600X',
 'AMD Ryzen 5 6400MT',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 5 7500F',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 5 7600X',
 'AMD Ryzen 5 9600X',
 'AMD Ryzen 5500',
 'AMD Ryzen 5X',
 'AMD Ryzen 7',
 'AMD Ryzen 7 255',
 'AMD Ryzen 7 260',
 'AMD Ryzen 7 2700',
 'AMD Ryzen 7 3800X',
 'AMD Ryzen 7 5700',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 7 5700U',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 5800X',
 'AMD Ryzen 7 6800H',
 'AMD Ryzen 7 7700',
 'AMD Ryzen 7 7700X',
 'AMD Ryzen 7 7730U',
 'AMD Ryzen 7 7800X3D',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 9800X3D',
 'AMD Ryzen 7640HS',
 'AMD Ryzen 9 3900X',
 'AMD Ryzen 9 6900HX',
 'AMD Ryzen 9 7900X',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 9 9900X',
 'AMD Ryzen 9 9900X3D',
 'AMD Ryzen 9 9950X',
 'AMD Ryzen 9 9950X3D',
 'Intel 12600H',
 'Intel 14450HX',
 'Intel G5905',
 'Intel Ultra 5',
 'Intel Ultra 7',
 'Intel Ultra 7 265F',
 'Intel Ultra 7 265K',
 'Intel Ultra 7 265KF',
 'Intel Ultra 9',
 'Intel Ultra 9 285K',
 'Intel Ultra 9 286K',
 'Intel Xeon E5',
 'Intel i3',
 'Intel i3 10100',
 'Intel i3 10100F',
 'Intel i3 10105',
 'Intel i5',
 'Intel i5 10400F',
 'Intel i5 10500',
 'Intel i5 11400F',
 'Intel i5 11600KF',
 'Intel i5 12400F',
 'Intel i5 13400F',
 'Intel i5 14400F',
 'Intel i5 6500',
 'Intel i5 7500',
 'Intel i5 8500',
 'Intel i5 9400F',
 'Intel i7',
 'Intel i7 10700K',
 'Intel i7 10700KF',
 'Intel i7 11700',
 'Intel i7 12700H',
 'Intel i7 13700F',
 'Intel i7 13700KF',
 'Intel i7 14700F',
 'Intel i7 14700K',
 'Intel i7 14700KF',
 'Intel i7 6700',
 'Intel i7 9700K',
 'Intel i7 Xeon',
 'Intel i9',
 'Intel i9 12900F',
 'Intel i9 12900KF',
 'Intel i9 13900F',
 'Intel i9 13900KF',
 'Intel i9 14900K',
 'Intel i9 14900KF',
 'Intel i9 9900K']

In [196]:
df_current['CPU'] = df_current['CPU'].str.replace('AMD Ryzen 4300U', 'AMD Ryzen 3 4300U', regex = False)
df_current['CPU'] = df_current['CPU'].str.replace('AMD Ryzen 5500', 'AMD Ryzen 5 5500', regex = False)
df_current['CPU'] = df_current['CPU'].str.replace('AMD Ryzen 5X', 'AMD Ryzen 5', regex = False)

df_current['CPU'] = df_current['CPU'].str.replace('AMD Ryzen 7640HS', 'AMD Ryzen 5 7640HS', regex = False)
df_current['CPU'] = df_current['CPU'].str.replace('Intel 12600H', 'Intel i5 12600H', regex = False)
df_current['CPU'] = df_current['CPU'].str.replace('Intel 14450HX', 'Intel i5 14450HX', regex = False)

In [197]:
df_current['CPU'].value_counts().sort_index().index.tolist()

['AMD Ryzen 3 3200G',
 'AMD Ryzen 3 4300U',
 'AMD Ryzen 3 5300G',
 'AMD Ryzen 3 5300U',
 'AMD Ryzen 5',
 'AMD Ryzen 5 2600',
 'AMD Ryzen 5 3400G',
 'AMD Ryzen 5 5500',
 'AMD Ryzen 5 5500U',
 'AMD Ryzen 5 5600',
 'AMD Ryzen 5 5600G',
 'AMD Ryzen 5 5600GT',
 'AMD Ryzen 5 5600X',
 'AMD Ryzen 5 6400MT',
 'AMD Ryzen 5 7430U',
 'AMD Ryzen 5 7500F',
 'AMD Ryzen 5 7600',
 'AMD Ryzen 5 7600X',
 'AMD Ryzen 5 7640HS',
 'AMD Ryzen 5 9600X',
 'AMD Ryzen 7',
 'AMD Ryzen 7 255',
 'AMD Ryzen 7 260',
 'AMD Ryzen 7 2700',
 'AMD Ryzen 7 3800X',
 'AMD Ryzen 7 5700',
 'AMD Ryzen 7 5700G',
 'AMD Ryzen 7 5700U',
 'AMD Ryzen 7 5700X',
 'AMD Ryzen 7 5800X',
 'AMD Ryzen 7 6800H',
 'AMD Ryzen 7 7700',
 'AMD Ryzen 7 7700X',
 'AMD Ryzen 7 7730U',
 'AMD Ryzen 7 7800X3D',
 'AMD Ryzen 7 8700F',
 'AMD Ryzen 7 8745HS',
 'AMD Ryzen 7 9700X',
 'AMD Ryzen 7 9800X3D',
 'AMD Ryzen 9 3900X',
 'AMD Ryzen 9 6900HX',
 'AMD Ryzen 9 7900X',
 'AMD Ryzen 9 8945HS',
 'AMD Ryzen 9 9900X',
 'AMD Ryzen 9 9900X3D',
 'AMD Ryzen 9 9950X',
 'AMD Ryzen 9 9950X3D',
 'Intel G5905',
 'Intel Ultra 5',
 'Intel Ultra 7',
 'Intel Ultra 7 265F',
 'Intel Ultra 7 265K',
 'Intel Ultra 7 265KF',
 'Intel Ultra 9',
 'Intel Ultra 9 285K',
 'Intel Ultra 9 286K',
 'Intel Xeon E5',
 'Intel i3',
 'Intel i3 10100',
 'Intel i3 10100F',
 'Intel i3 10105',
 'Intel i5',
 'Intel i5 10400F',
 'Intel i5 10500',
 'Intel i5 11400F',
 'Intel i5 11600KF',
 'Intel i5 12400F',
 'Intel i5 12600H',
 'Intel i5 13400F',
 'Intel i5 14400F',
 'Intel i5 14450HX',
 'Intel i5 6500',
 'Intel i5 7500',
 'Intel i5 8500',
 'Intel i5 9400F',
 'Intel i7',
 'Intel i7 10700K',
 'Intel i7 10700KF',
 'Intel i7 11700',
 'Intel i7 12700H',
 'Intel i7 13700F',
 'Intel i7 13700KF',
 'Intel i7 14700F',
 'Intel i7 14700K',
 'Intel i7 14700KF',
 'Intel i7 6700',
 'Intel i7 9700K',
 'Intel i7 Xeon',
 'Intel i9',
 'Intel i9 12900F',
 'Intel i9 12900KF',
 'Intel i9 13900F',
 'Intel i9 13900KF',
 'Intel i9 14900K',
 'Intel i9 14900KF',
 'Intel i9 9900K']

In [198]:
df_current

,Title,Rating,Rating Count,Price,URL,Site,CPU,GPU,RAM,Storage,OS
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",4.1,269,909.0,https://www.newegg.com/alcpok-gaming-desktop-p...,Newegg,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,1TB NVMe,Windows 11
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,4.1,2,939.0,https://www.newegg.com/p/3D5-003E-00H23,Newegg,Intel i5 13400F,NVIDIA RTX 3050,16GB DDR4,1TB SSD,Windows 11
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,4.3,6,675.0,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,Newegg,AMD Ryzen 5 5600G,Integrated,16GB DDR4,1TB NVMe,Windows 10 Pro
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,4.1,1,624.0,https://www.newegg.com/viprtech-stryker-gaming...,Newegg,Intel i5 9400F,AMD RX 580,16GB DDR4,500GB SSD,Windows 11 Pro
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,4.1,1,1152.0,https://www.newegg.com/hp-gaming-desktop-pcs-g...,Newegg,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,1TB SSD,Windows 11 Home
...,...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,4.2,156,1299.0,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Amazon,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,2TB SSD,Windows 11 Pro
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,4.7,244,999.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 5700,Integrated,16GB DDR4,1TB NVMe,Windows 11
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,4.1,1,1049.0,https://www.bestbuy.com/product/velztorm-pilum...,BestBuy,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB DDR4,1TB SSD,Windows 11
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,4.7,162,1699.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB DDR4,1TB NVMe,Windows 11
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,4.1,35,1099.0,https://www.bestbuy.com/product/skytech-gaming...,BestBuy,Intel i5 14400F,AMD RX 9060 XT,16GB DDR4,1TB NVMe,Windows 11

In [199]:
df_current['Storage'].value_counts().sort_index().index.tolist()

['11TB SSD',
 '1TB HDD',
 '1TB NVMe',
 '1TB SSD',
 '240GB SSD',
 '256GB NVMe',
 '256GB SSD',
 '2TB HDD',
 '2TB NVMe',
 '2TB SSD',
 '3TB SSD',
 '4TB NVMe',
 '4TB SSD',
 '500GB NVMe',
 '500GB SSD',
 '512GB NVMe',
 '512GB SSD',
 '5TB SSD',
 '8TB SSD']

In [200]:
df_cleaned = df_current.copy()

In [201]:
df_current = df_current[['Title', 'URL', 'CPU', 'GPU', 'RAM', 'Storage', 'OS', 'Rating', 'Rating Count', 'Price']]

In [202]:
df_current

,Title,URL,CPU,GPU,RAM,Storage,OS,Rating,Rating Count,Price
4,"Used - Like New ALCPOK Gaming PC Desktop,Prebu...",https://www.newegg.com/alcpok-gaming-desktop-p...,AMD Ryzen 5 5600X,NVIDIA RTX 5060,32GB DDR4,1TB NVMe,Windows 11,4.1,269,909.0
8,Hoengager Gaming PC -Intel i5 13400F -GeForce ...,https://www.newegg.com/p/3D5-003E-00H23,Intel i5 13400F,NVIDIA RTX 3050,16GB DDR4,1TB SSD,Windows 11,4.1,2,939.0
11,AVGPC Mini Series Gaming PC - Ryzen 5 5600G 3....,https://www.newegg.com/avgpc-mini-b-6600xt/p/3...,AMD Ryzen 5 5600G,Integrated,16GB DDR4,1TB NVMe,Windows 10 Pro,4.3,6,675.0
12,ViprTech Stryker 1.0 Gaming PC - Intel i5-9400...,https://www.newegg.com/viprtech-stryker-gaming...,Intel i5 9400F,AMD RX 580,16GB DDR4,500GB SSD,Windows 11 Pro,4.1,1,624.0
14,HP OMEN 16L Gaming Desktop AMD Ryzen 7 8700F N...,https://www.newegg.com/hp-gaming-desktop-pcs-g...,AMD Ryzen 7 8700F,NVIDIA RTX 5060,16GB DDR5,1TB SSD,Windows 11 Home,4.1,1,1152.0
...,...,...,...,...,...,...,...,...,...,...
3567,msi Infinite RS AI Gaming Desktop: Intel Ultra...,https://www.amazon.com/MSI-Infinite-Gaming-Des...,Intel Ultra 9,NVIDIA RTX 5090,64GB DDR5,2TB SSD,Windows 11 Pro,4.2,156,1299.0
3666,Skytech Gaming - Skytech ARCH4 - AMD Ryzen 7 5...,https://www.bestbuy.com/product/skytech-gaming...,AMD Ryzen 7 5700,Integrated,16GB DDR4,1TB NVMe,Windows 11,4.7,244,999.0
3667,Velztorm - Pilum Pre-Built Gaming Desktop PC (...,https://www.bestbuy.com/product/velztorm-pilum...,AMD Ryzen 7 5700X,NVIDIA RTX 5060,32GB DDR4,1TB SSD,Windows 11,4.1,1,1049.0
3668,Skytech Gaming - KING95 Gaming Desktop PC - AM...,https://www.bestbuy.com/product/skytech-gaming...,AMD Ryzen 7 9700X,NVIDIA RTX 5060 Ti,16GB DDR4,1TB NVMe,Windows 11,4.7,162,1699.0
3669,Skytech Gaming - Skytech AZURE3 - Intel Core i...,https://www.bestbuy.com/product/skytech-gaming...,Intel i5 14400F,AMD RX 9060 XT,16GB DDR4,1TB NVMe,Windows 11,4.1,35,1099.0

In [203]:
df_cleaned = df_current.copy()

In [204]:
df_cleaned.to_csv('prebuilt_pcs_cleaned.csv')